### PR TITLE
ScheduledTask: Add 'StopExisting' to valid values for MultipleInstances parameter

### PR DESCRIPTION
**Pull request by Rob-S**
#### Pull Request (PR) description
Add 'StopExisting' to valid values for ScheduledTask MultipleInstances parameter - fixes Issue #333

#### This Pull Request (PR) fixes the following issues
Fixes Issue #333 

#### Task list
- [√] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [√] Resource documentation added/updated in README.md in resource folder.
- [√] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [N/A] Comment-based help added/updated.
- [N/A] Localization strings added/updated in all localization files as appropriate.
- [N/A] Examples appropriately added/updated.
- [√] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [N/A] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [√] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/335)

### CODE REVIEW

**Comment by Rob-S** [comment]
The HQRM tests are failing with the error below for all the examples for _every_ resource, saying `Use Import-DSCResource to import the resource.`  However, the examples _do_ import the resources using the module name: `Import-DscResource -ModuleName ComputerManagementDsc`. Has something gone awry with the tests?

```
    Context ScheduledTask\1-ScheduledTask_CreateScheduledTaskOnce_Config.ps1
      [-] Should compile MOFs for example correctly 86ms
        Expected no exception to be thrown, but an exception "At D:\a\1\s\source\Examples\Resources\ScheduledTask\1-ScheduledTask_CreateScheduledTaskOnce_Config.ps1:35 char:9
        +         ScheduledTask ScheduledTaskOnceAdd
        +         ~~~~~~~~~~~~~
        Undefined DSC resource 'ScheduledTask'. Use Import-DSCResource to import the resource." was thrown from D:\a\1\s\source\Examples\Resources\ScheduledTask\1-ScheduledTask_CreateScheduledTaskOnce_Config.ps1:35 char:9
            +         ScheduledTask ScheduledTaskOnceAdd
            +         ~~~~~~~~~~~~~.
        141:                     } | Should -Not -Throw
        at <ScriptBlock>, D:\a\1\s\output\RequiredModules\DscResource.Test\0.13.0\Tests\QA\ExampleFiles.common.Tests.ps1: line 27
```

**Comment by PlagueHO** [comment]
Hi @Rob-S - this is due to a change to recent ModuleBuilder change. I've got a PR #334 open that will resolve it. Once that is trough the build should work properly again.

**Comment by PlagueHO** [comment]
You should be able to rebase and resolve conflicts and tests should pass.

**Comment by Rob-S** [comment]
Does anything else need done on this?

**Comment by PlagueHO** [comment]
Hi @Rob-S - sorry, this is on me. I'll review this weekend (this week is a bit crazy with MS Build and so none of my evenings are free).

**Comment by PlagueHO** [comment]
Hi @Rob-S - the build failure is caused by a recent release of Module Builder. I've fixed the issue in this PR https://github.com/dsccommunity/ComputerManagementDsc/pull/334 - if you rebase onto master again the build should pass - then we can take a look at the integration tests.

**Comment by PlagueHO** [comment]
Hi @Rob-S - Sorry, correction, the issue you're seeing is because of the Pester v5.x release. I'm going to pin this module to remain on Pester 4.10.1.

**Comment by PlagueHO** [comment]
Once this PR https://github.com/dsccommunity/ComputerManagementDsc/pull/337 is through you can rebase and the tests will hopefully pass.

**Comment by PlagueHO** [comment]
@Rob-S - can you try rebasing your branch onto master again to see if that fixes the build?

**Comment by PlagueHO** [comment]
Hi @Rob-S - looks like the tests are failing. I think this may be because:https://dev.azure.com/dsccommunity/ComputerManagementDsc/_build/results?buildId=2305&view=logs&j=158455ef-2db5-56fd-6022-83ded799e050&t=b737ddad-5217-50db-260a-b6e0dd548ea1&l=933

**Comment by Rob-S** [comment]
@PlagueHO Yes, I had fixed the tests around the same time you entered that comment. But the actual change I made to fix Get-CurrentResource is the one thing that is still failing the tests. When I run it myself locally, it works fine; it's just failing in the tests.

On line 157 of DSC_ScheduledTask.Tests.ps1 where it has:
`$result = Get-TargetResource @getTargetResourceParameters`
what we really need to do is get the parameters from the actual target resource that was affected by the previously executed Set-TargetResource on line 153 (rather than the parameters variable). I'm not familiar with the test syntax, particularly the "@" variables and don't see anywhere else in that test script where Get-TargetResource follows the Set-TargetResource -- Set-TargetResource is always after the Get-TargetResource. For the test that is failing, the Set-TargetResource sets the value in the CimInstanceProperties, and that's the value that needs to be retrieved by Get-TargetResource.

Do you know how, in the test script, to reference the resource affected by Set-TargetResource?

**Comment by Rob-S** [comment]
@PlagueHO Moving the Get-TargetResource into the "It" block didn't help. Just to prove to myself that it wasn't just the test for the change that I had made... I had noticed that the test starting on line 126 under "No scheduled task exists, but it should" did not actually test in "Should create the scheduled task in the set method" to ensure that the resource was _actually_ created by Set-TargetResource. When I added the `$result.Ensure | Should -Be 'Present'` on line 129 it failed as well, indicating that the resource was still `Absent` after Set-TargetResource.

Do you see anything wrong with the way that test, the one starting on line 126, is coded, where the resource is still 'Absent' after it was supposedly created by Set-TargetResource?

**Comment by Rob-S** [comment]
> I think what we need is a unit test that tests when `MultipleInstances` is set to `StopExisting`. I could be wrong, but I didn't see one. Is it easy to add that?

No. It's easy to add it for the other values, but not for StopExisting, since the Enum does not support that. See the comments for my commits when I attempted to do that.

**Pull request merged**
