### PR TITLE
Miscellaneous Pipeline Changes

### LINKED ISSUE #294: ScheduledTask resource Credential parameter with Domain\ prefix
I have a job as following, but it reports the state as incorrect because of the credential. It appears I am setting it as 'username' but then the scheduled task is taking that and just setting it as DOMAIN\username, leading to a mismatch.  I think I can probably hack it to work somehow, but ideally the scheduledtask resource should probably evaluate DOMAIN\username the same as username.

ScheduledTask 'DRBackup' {
            TaskName = 'DRBackup'
            TaskPath = '\8203Jobs\'
            ActionExecutable = 'C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe'
            ActionArguments = "-Command $BackupJob_Cmd1 $BackupJob_Cmd2"
            ScheduleType = 'Daily'
            StartTime = Get-Date '3am'
            ExecuteAsCredential = $DomainAdminCred
            RunLevel = 'Highest'
            DependsOn = '[cPowerShellModuleManagement]EventLogTools','[xEventLog]CustomLog','[cPowerShellModuleManagement]DRBackupTools'
        }

Verbose Output from Test
VERBOSE: [NOAA8203-MGMT1]: LCM:  [ Start  Resource ]  [[ScheduledTask]DRBackup]
VERBOSE: [NOAA8203-MGMT1]: LCM:  [ Start  Test     ]  [[ScheduledTask]DRBackup]
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] Testing scheduled task 'DRBackup' in '\8203Jobs\'.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] Getting current scheduled task values for task 'DRBackup' in '\8203Jobs\'.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] Task 'DRBackup' found in '\8203Jobs\'. Retrieving settings, first action, first trigger and repetition
settings.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] Detected schedule type 'Daily' for first trigger.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] Current scheduled task values for task 'DRBackup' in '\8203Jobs\' retrieved.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] Testing DSC parameter state.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] MATCH: Value (type 'System.String') for property 'StartTime' does match. Current state is
'2019-12-02T03:00:00' and desired state is '2019-12-02T03:00:00'.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] MATCH: Value (type 'System.String') for property 'ActionExecutable' does match. Current state is
'C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe' and desired state is 'C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe'.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] MATCH: Value (type 'System.String') for property 'ActionArguments' does match. Current state is '-Command
Start-DRBackup -DPMProtectionGroupName DisasterRecovery -Destination \\noaa8203-ds1817\DRBackup -Verbose *>&1 | % {$i++;Write-StreamToEventLog -ID $i -Stream $_ -Logname Application
-Source DRBackupTools}' and desired state is '-Command Start-DRBackup -DPMProtectionGroupName DisasterRecovery -Destination \\noaa8203-ds1817\DRBackup -Verbose *>&1 | %
{$i++;Write-StreamToEventLog -ID $i -Stream $_ -Logname Application -Source DRBackupTools}'.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] NOTMATCH: Value **(type 'System.String') for property 'ExecuteAsCredential' does not match. Current state is
 'NOAA8203\powershelljobs_svc' and desired state is 'powershelljobs_svc'.**
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] MATCH: Value (type 'System.String') for property 'TaskPath' does match. Current state is '\8203Jobs\' and
desired state is '\8203Jobs\'.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] MATCH: Value (type 'System.String') for property 'ScheduleType' does match. Current state is 'Daily' and
desired state is 'Daily'.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] MATCH: Value (type 'System.String') for property 'TaskName' does match. Current state is 'DRBackup' and
desired state is 'DRBackup'.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] MATCH: Value (type 'System.String') for property 'RunLevel' does match. Current state is 'Highest' and
desired state is 'Highest'.
VERBOSE: [NOAA8203-MGMT1]:                            [[ScheduledTask]DRBackup] Test-DscParameter result is 'False'.
VERBOSE: [NOAA8203-MGMT1]: LCM:  [ End    Test     ]  [[ScheduledTask]DRBackup] False in 0.5940 seconds.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

### LINKED ISSUE #323: ScheduledTask: Resource is never in compliance when BuiltInAccount is used
### Details of the scenario you tried and the problem that is occurring
I am trying to apply a configuration using the ScheduledTask resource and the BuiltInAccount property.
Whilst the configuration applies successfully, running Test-DscConfiguration always returns false.
This ultimately seems to boil down to the SYSTEM principal account name sometimes displaying as 'SYSTEM' and other times as 'NT AUTHORITY\SYSTEM'.

#### Verbose logs showing the problem
```
VERBOSE: [ServerName]:[[ScheduledTask]Dsc_ScheduledTask_Taskname] MATCH: Value (type 'System.String') for property 
'LogonType' does match. Current state is 'ServiceAccount' and desired state is 'ServiceAccount'.
VERBOSE: [ServerName]:[[ScheduledTask]Dsc_ScheduledTask_Taskname] MATCH: Value (type 'System.String') for property 
'User' does match. Current state is 'SYSTEM' and desired state is 'SYSTEM'.
VERBOSE: [ServerName]:[[ScheduledTask]Dsc_ScheduledTask_Taskname] NOTMATCH: Value (type 'System.String') for property
 'BuiltInAccount' does not match. Current state is 'SYSTEM' and desired state is 'NT AUTHORITY\SYSTEM'.
VERBOSE: [ServerName]:[[ScheduledTask]Dsc_ScheduledTask_Taskname] MATCH: Value (type 'System.String') for property 
'ExecuteAsCredential' does match. Current state is 'SYSTEM' and desired state is 'SYSTEM'.
```
#### Suggested solution to the issue
My guess is that when commit 1ae52d58a809b5604101dc1bf443e478ac34b88c was implemented it didn't go far enough to resolve the underlying issue OR a recent Windows Update has changed the operation of the Get-ScheduledTask cmdlet and the values it returned.

I believe a change needs to be made to source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1, most likely in the section of code below:

Current:
```
Function Get-CurrentResource
...
if (($result.ContainsKey('LogonType')) -and ($result['LogonType'] -ieq 'ServiceAccount'))
{
    $result.Add('BuiltInAccount', $task.Principal.UserId)
}
...
```

Proposed:
```
Function Get-CurrentResource
...
if (($result.ContainsKey('LogonType')) -and ($result['LogonType'] -ieq 'ServiceAccount'))
{
    switch ($task.Principal.UserId -like 'NT AUTHORITY\*')
    {
        $true  {$result.Add('BuiltInAccount', $task.Principal.UserId)}
        $false {$result.Add('BuiltInAccount', "NT AUTHORITY\$($task.Principal.UserId)")}
    }
}
...
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
ScheduledTask Dsc_ScheduledTask_Taskname
{
    TaskName           = "Remove Log Files"
    ActionArguments    = "-ExecutionPolicy Bypass -NonInteractive -Command Remove-LogFile -Path 'D:\Temp' -Recurse -Filter '*' -Age 30"
    ActionExecutable   = '%WINDIR%\System32\WindowsPowerShell\v1.0\powershell.exe'
    BuiltInAccount     = 'SYSTEM'
    DaysInterval       = 1
    Description        = 'Remove all temporary files older than 30 days from "D:\Temp".'
    Enable             = $true
    Ensure             = 'Present'
    ExecutionTimeLimit = '01:00:00'
    MultipleInstances  = 'IgnoreNew'
    RunLevel           = 'Highest'
    ScheduleType       = 'Daily'
    StartTime          = '2019-09-17 23:56:00'
    StartWhenAvailable = $true
    TaskPath           = '\'
}
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.3630.amd64fre.rs1_release.200407-1730
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3471
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
master (version 8.1.0 downloaded from PowerShell Gallery)

### LINKED ISSUE #324: Correct Pipeline Include Path in Azure Pipeline Build YAML
This is because a recent change to Azure DevOps Pipelines has removed the ability to use `**` in Include/Exclude paths.

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#wildcards

dsccommunity/ActiveDirectoryDsc#599

### LINKED ISSUE #325: Update to Use Latest Version of ModuleBuilder and merge HISTORIC_CHANGELOG
Update to use latest version of ModuleBuilder module. This also allows merging the HISTORIC_CHANGELOG.MD into the CHANGELOG.MD.

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

Update ModuleBuilder to Latest.
Merge HISTORIC_CHANGELOG.md into CHANGELOG.md.
Change Azure DevOps Pipeline trigger to include `source/*`.

This PR also includes a fix for #323.

I also a known issue info to address #294.

#### This Pull Request (PR) fixes the following issues

- Fixes #324
- Fixes #325
- Fixes #323 
- Fixes #294

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing for me?

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/326)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hold off on this one @johlju - I'm not sure why Integration tests are failing. There wasn't any change that would have affected that so it may be something that has changed with the agent.

**Comment by johlju** [comment]
No worries. Let me know when it is ready to review. 🙂

**Comment by PlagueHO** [comment]
Hi @johlju - this PR is now ready to review. I had to make some additional changes to get the tests to pass.

**Comment by johlju** [comment]
Closing and reopening to kick of the tests again since it failed on. I have seen this when the previous run is to fast to the LCM haven't time to cooldown.

```
CimException: Cannot invoke the Get-DscConfiguration cmdlet. The Consistency Check or Pull
cmdlet is in progress and must return before Get-DscConfiguration can be invoked. Use -Force 
option if that is available to cancel the current operation.
``` 

https://dev.azure.com/dsccommunity/ComputerManagementDsc/_build/results?buildId=1818&view=logs&j=bed57fa5-efa2-5e6c-3967-59915169b168&t=5a0501c2-c194-508e-8f56-358cb6bbc353&l=383

In xWebAdministration and SqlServerDsc I have added the following helper function between tests where this happens (not everywhere though). Might be better to add it to `Initialize-TestEnvironment`.

https://github.com/dsccommunity/SqlServerDsc/blob/fab9419549a490efab38e070e8eda40d2a10d531/tests/TestHelpers/CommonTestHelper.psm1#L398-L409

**Comment by PlagueHO** [comment]
Thanks for that @johlju . In other resources we used to use the Reset-Dsc function that was part of the Test initialization and/or test helper, but this got eliminated by the move to the new CI process. I meant to add something back in but haven't had time. I created this many years back for xPSDesiredStateConfiguration I think. Anyway, I'll aim to roll your fix in.

**Comment by PlagueHO** [comment]
Sidenote: the reason why we decided to force the LCM to stop (Reset-Dsc) rather than to wait is that the LCM on occasion took a long time to complete so forcing a stop resulted in faster test completion in these situations. xPSDesiredStateConfiguration was very problematic here (often jamming up multiple times in a single CI run).

**Comment by johlju** [comment]
Aha, so maybe that is why we are starting to see these error because "Reset-Dsc" was removed. I'm good with `Reset-Dsc" too if it helps tests to run faster. But the `Wait-ForIdleLcm` has worked perfectly. I seen it at the most wait up to 8 seconds to continue (4 retries). Though, that is 8 seconds we could save with "Reset-Dsc". 🙂

**Comment by PlagueHO** [comment]
I'm OK either way - but it would be good if we could unify the functions everywhere. E.g. Perhaps create a DscResource.TestHelper module that contains some of this shared code. Not that it is really a big deal replicating it between modules.

Anyway, I've raised some issues in they key repos where this is a problem and will address when I get time (need to do some more module conversions to new CI tonight).

**Comment by johlju** [comment]
I agree a test helper module would be great, I thought about that too.

**Pull request merged**
