### PR TITLE
Add new resource IEEnhancedSecurityConfiguration

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
This moves the resource xIEEsc from module xSystemSecurity and renames it to IEEnhancedSecurityConfiguration.

#### This Pull Request (PR) fixes the following issues
- part of issue https://github.com/PowerShell/DscResources/issues/374

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/300)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Sweet! @johlju - I'll trade you: Can you review this one for me? It would be good to get this in after I complete the move to the new CI pipeline. #299

**Comment by johlju** [comment]
Yep, better to get thios one in after the module is converted.

**Comment by johlju** [comment]
@PlagueHO You could have re-targeted this PR against master instead of closing (where you edit the PR title). I open a new one since I can't re-open this one.

**Comment by PlagueHO** [comment]
I didn't actually close it - it closed automatically when the dev branch was deleted :cry:

**Comment by PlagueHO** [comment]
Which is why I don't have a "reopen" button:
image

:grin:

**Comment by johlju** [comment]
Yep, need to re-target all PR's before removing the dev branch. 🙂  It's in the "Steps" 😉

**Comment by johlju** [comment]
No worries. But sad for those other PR's that might have been open, they won't know why it was closed. :/

**Comment by PlagueHO** [comment]
I'll go through and comment on them. I've already commented on the ones that weren't flagged as abandoned.

**Comment by PlagueHO** [comment]
Doh! Must have missed that step - I think I forgot where I was in the process a few times.

**Pull request closed without merging**
