### PR TITLE
Fix and Update Pipeline files to latest pattern - Fixes #383

### LINKED ISSUE #382: Update Azure DevOps Pipeline Images
The Ubuntu 16.04 and Windows Server 2016 Azure DevOps pipeline hosted images will be deprecated:

https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/

The pipeline stages need to be migrated to newer versions.

### LINKED ISSUE #383: Update CI Pipeline Files from Latest Pattern
Copy the latest patterns for the `build.yml`, `build.ps1` and `azure-pipelines.yml` from the PR:
https://github.com/dsccommunity/xExchange/pull/471

# build.yml

```
####################################################
#      DscResource.DocGenerator Configuration      #
####################################################
DscResource.DocGenerator:
  Generate_Conceptual_Help:
    MarkdownCodeRegularExpression:
      - '\`(.+?)\`' # Match inline code-block
      - '\\(\\)' # Match escaped backslash
      - '\[[^\[]+\]\((.+?)\)' # Match markdown URL
      - '_(.+?)_' # Match Italic (underscore)
      - '\*\*(.+?)\*\*' # Match bold
      - '\*(.+?)\*' # Match Italic (asterisk)
```

```
  publish:
    - publish_module_to_gallery
    - Publish_Release_To_GitHub
    - Publish_GitHub_Wiki_Content
    - Create_ChangeLog_GitHub_PR
```

- Also add updated issue templates and related files:
- .github\ISSUE_TEMPLATE
- .github\CONTRIBUTING.md
- .github\PULL_REQUEST_TEMPLATE.md
- .github\ISSUE_TEMPLATE\General.md
- .github\ISSUE_TEMPLATE\Problem_with_resource.yml
- .github\ISSUE_TEMPLATE\Resource_proposal.yml
- .github\ISSUE_TEMPLATE\config.yml

Add SECURITY.md as well.

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR updates the pipeline files and github templates to the latest versions. It also fixes the GitVersion task and updates the pipeline agents.

#### This Pull Request (PR) fixes the following issues

- Fixes #383 
- Fixes #382 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing when you have a moment?

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/384)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/384)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

*[a discussion](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/384#-N-HR3UC1TGVctDaBexY:-N-HR3UC1TGVctDaBexZ:b-ddrtid) (no related file):*
We need to remove the files:
- .github/ISSUE_TEMPLATE/Problem_with_resource.md
- .github/ISSUE_TEMPLATE/Resource_proposal.md

They can not be deleted by the template (as far as I know).

---

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/384)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/384#-N-HR3UC1TGVctDaBexY:-N-HVh4g5oVhSCVsD_tu:bcpb1wg) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We need to remove the files:
- .github/ISSUE_TEMPLATE/Problem_with_resource.md
- .github/ISSUE_TEMPLATE/Resource_proposal.md

They can not be deleted by the template (as far as I know).
</blockquote></details>

Good catch. Removed. Thanks @johlju 

---

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/384#-:-N-HWLHh3GkVtgAKn_Fz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

**Review by johlju — APPROVED** [review]

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/384#-:-N-HWlxa1I9cdauIxdh9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Comment by johlju** [comment]
Not sure why Reviewable "is waiting" for you. 🤔  All good, no more comments. Waiting for the tests to pass then we can merge. 🙂

**Comment by johlju** [comment]
@PlagueHO it seems this PR need to be rebased...

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/384#-:-N-HYcLy0vGu7u2QVwBA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Comment by PlagueHO** [comment]
Thanks @johlju - rebased now. Hopefully tests pass and will then merge. Working on NetworkingDsc now. Will try and get through all the rest this week (finally getting some free time to work on DSC 😁 )

**Comment by johlju** [comment]
I will review them as soon as I can 🙂  I see the e-mails when you tag me 🙂

**Pull request merged**
