### PR TITLE
Fix mismatch between user and builtinaccount

### LINKED ISSUE #385: ScheduledTask: Get-TargetResource returns wrong account for BuiltInAccount parameter
### Problem description

The ScheduledTask resource parameter `BuiltInAccount` must be one of the following: `('SYSTEM', 'LOCAL SERVICE', 'NETWORK SERVICE')`, but `Get-TargetResource` returns `BuiltInAccount` as `NT SERVICE\SYSTEM`. 

### Verbose logs

```text
: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = Resourceget,'className' = MSFT_DSCLocalConfigurationManager,'n
amespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer IAD3DRND-D09-1 with user sid S-1-5-21-2851708077-3393195298-855477758-112710.
VERBOSE: [IAD3DRND-D09-1]:                            [[ScheduledTask]DirectResourceAccess] Getting scheduled task 'Cleanup_DSC_ConfigurationStatus_Fol
der' in '\'.
VERBOSE: [IAD3DRND-D09-1]:                            [[ScheduledTask]DirectResourceAccess] Getting current scheduled task values for task 'Cleanup_DSC
_ConfigurationStatus_Folder' in '\'.
VERBOSE: [IAD3DRND-D09-1]:                            [[ScheduledTask]DirectResourceAccess] Task 'Cleanup_DSC_ConfigurationStatus_Folder' found in '\'.
 Retrieving settings, first action, first trigger and repetition settings.
VERBOSE: [IAD3DRND-D09-1]:                            [[ScheduledTask]DirectResourceAccess] Detected schedule type 'Daily' for first trigger.
VERBOSE: [IAD3DRND-D09-1]:                            [[ScheduledTask]DirectResourceAccess] Current scheduled task values for task 'Cleanup_DSC_Configu
rationStatus_Folder' in '\' retrieved.
VERBOSE: [IAD3DRND-D09-1]: LCM:  [ End    Get      ]  [[ScheduledTask]DirectResourceAccess]  in 0.8790 seconds.
VERBOSE: [IAD3DRND-D09-1]: LCM:  [ End    Set      ]    in  1.5740 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 1.711 seconds

PS C:\Windows\system32> $result


ConfigurationName               : 
DependsOn                       : 
ModuleName                      : c:/puppet-dsc/sdk/computermanagementdsc/lib/puppet_x/computermanagementdsc/dsc_resources/ComputerManagementDsc/Compu
                                  terManagementDsc.psd1
ModuleVersion                   : 8.4.0
PsDscRunAsCredential            : 
ResourceId                      : 
SourceInfo                      : 
ActionArguments                 : /c "del /q /s c:\windows\system32\configuration\configurationstatus\* > nul"
ActionExecutable                : cmd.exe
ActionWorkingPath               : 
AllowStartIfOnBatteries         : False
BuiltInAccount                  : SYSTEM
Compatibility                   : Win7
DaysInterval                    : 1
DaysOfWeek                      : {}
Delay                           : 00:00:00
Description                     : 
DisallowDemandStart             : False
DisallowHardTerminate           : False
DisallowStartOnRemoteAppSession : False
DontStopIfGoingOnBatteries      : False
DontStopOnIdleEnd               : False
Enable                          : True
Ensure                          : Present
EventSubscription               : 
ExecuteAsCredential             : MSFT_Credential
ExecuteAsGMSA                   : SYSTEM
ExecutionTimeLimit              : 00:20:00
Hidden                          : False
IdleDuration                    : 01:00:00
IdleWaitTimeout                 : 02:00:00
LogonType                       : ServiceAccount
MultipleInstances               : Queue
NetworkName                     : 
Priority                        : 7
RandomDelay                     : 00:00:00
RepeatInterval                  : 00:00:00
RepetitionDuration              : Indefinitely
RestartCount                    : 0
RestartInterval                 : 00:00:00
RestartOnIdle                   : False
RunLevel                        : Limited
RunOnlyIfIdle                   : False
RunOnlyIfNetworkAvailable       : False
ScheduleType                    : Daily
StartTime                       : 4/27/2022 4:00:00 AM
StartWhenAvailable              : False
SynchronizeAcrossTimeZone       : False
TaskName                        : Cleanup_DSC_ConfigurationStatus_Folder
TaskPath                        : \
User                            : NT AUTHORITY\SYSTEM
WakeToRun                       : False
WeeksInterval                   : 0
PSComputerName                  : localhost
```

### DSC configuration

```powershell
$InvokeParams = @{
  Name = 'ScheduledTask'; 
  Method = 'get'; 
  Property = @{
    taskname = 'Cleanup_DSC_ConfigurationStatus_Folder'}; 
    ModuleName = @{ModuleName = 'c:/puppet-dsc/sdk/computermanagementdsc/lib/puppet_x/computermanagementdsc/dsc_resources/ComputerManagementDsc/ComputerManagementDsc.psd1'; 
    RequiredVersion = '8.4.0'
    }
}
  $Result = Invoke-DscResource @InvokeParams
```

### Suggested solution

Update `Get-CurrentResource` function to not prepend the `DomainName` `NT AUTHORITY`, or update the valid set for `BuiltInAccount` to include `NT Authority\SYSTEM`

L1888 of `Get-CurrentResource` :
```       
 if (($result.ContainsKey('LogonType')) -and ($result['LogonType'] -ieq 'ServiceAccount'))
        {
            # $builtInAccount = Set-DomainNameInAccountName -AccountName $task.Principal.UserId -DomainName 'NT AUTHORITY'
            # $result.Add('BuiltInAccount', $builtInAccount)
            $result.Add('BuiltInAccount', $task.Principal.UserId)
        }
```

### Operating system the target node is running

```text
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

```

### PowerShell version and build the target node is running

```text
PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                                                  
----                           -----                                                                                                                  
PSVersion                      5.1.17763.2268                                                                                                         
PSEdition                      Desktop                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                
BuildVersion                   10.0.17763.2268                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                        
WSManStackVersion              3.0                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                    
SerializationVersion           1.1.0.1
```

### ComputerManagementDsc version

```text
8.4.0
```

### PR DESCRIPTION
**Pull request by nickgw**
Currently `ScheduledTask` conflates the param `BuiltInAccount` and `*-ScheduledTask` cmdlet's `user` parameter. This fixes that.

#### Pull Request (PR) description

Currently `ScheduledTask` conflates the param `BuiltInAccount` and `*-ScheduledTask` cmdlet's `user` parameter. This fixes that.

#### This Pull Request (PR) fixes the following issues

- Fixes #385 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387)

### CODE REVIEW

**Comment by ShawnHardwick** [comment]
Should the MOF schema be updated to match this as well?

https://github.com/dsccommunity/ComputerManagementDsc/blob/main/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.schema.mof#L16

**Comment by nickgw** [comment]
> Should the MOF schema be updated to match this as well?
> 
> https://github.com/dsccommunity/ComputerManagementDsc/blob/main/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.schema.mof#L16

The inputs don't actually change. The code was comparing the wrong properties.

**Comment by PlagueHO** [comment]
Hi @nickgw - sorry was tied up on other things. I'll get onto this close to the end of the week. Just need to try and avoid breaking Windows Server 2016 (unfortunately we can't test on it at the moment unless we get something like TK going in Azure).

**Comment by nickgw** [comment]
Hey @PlagueHO just bumping this (and my related comments in the issue) when you get a chance!

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387)* status: all files reviewed, 4 unresolved discussions (waiting on @nickgw)

___
*[`CHANGELOG.md` line 7 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-N78OggP1GiuzL7-pH-7:-N78OggP1GiuzL7-pH-8:bdj1dko) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ee9648b1cc8e93dea3a854414961b0aad76769fe/CHANGELOG.md#L7)):*
> ```Markdown
> 
> ## [Unreleased]
> ### Fixed
> ```

Can you add a blank line above this line?
___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 832 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-N786OV226Plr-evxq3S:-N786OV226Plr-evxq3T:b-qh2gvr) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ee9648b1cc8e93dea3a854414961b0aad76769fe/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L832)):*
> ```PowerShell
>                 instead?
>             #>
>             $username = Set-DomainNameInAccountName -AccountName SYSTEM -DomainName 'NT AUTHORITY'
> ```

Nit: Just for consistency, can you put single quotes around `SYSTEM`?
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 1784 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-N787FSC5gR7-aeTpl6G:-N787FSDB14-PitcEM7H:b9bbsik) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ee9648b1cc8e93dea3a854414961b0aad76769fe/tests/Unit/DSC_ScheduledTask.Tests.ps1#L1784)):*
> ```PowerShell
>                 }
> 
>                 # It 'Should Disregard ExecuteAsCredential and Set User to the BuiltInAccount' {
> ```

If a test isn't verifying the correct thing, we should remove it rather than commenting. However, in this case, I think the test should be adjusted to reflect the actual function. 
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 1791 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-N78OnZn7rBanVq3gIpw:-N78OnZn7rBanVq3gIpx:bbraqij) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ee9648b1cc8e93dea3a854414961b0aad76769fe/tests/Unit/DSC_ScheduledTask.Tests.ps1#L1791)):*
> ```PowerShell
>                 # }
> 
>                 $testParameters.Add('LogonType', 'Password')
> ```

Can you also add some additional tests here to verify the changed functionallity?

**Comment by nickgw** [comment]
@PlagueHO Do you mind taking another look at this? I've added another test.

**Review by nickgw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 7 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-N78OggP1GiuzL7-pH-7:-NFkv6U20xjcS_x7Hbx1:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ee9648b1cc8e93dea3a854414961b0aad76769fe/CHANGELOG.md#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line above this line?
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 1784 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-N787FSC5gR7-aeTpl6G:-NFkvBpVANDLpPL1KzWr:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ee9648b1cc8e93dea3a854414961b0aad76769fe/tests/Unit/DSC_ScheduledTask.Tests.ps1#L1784)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

If a test isn't verifying the correct thing, we should remove it rather than commenting. However, in this case, I think the test should be adjusted to reflect the actual function. 
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 1791 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-N78OnZn7rBanVq3gIpw:-NFkvIkXDdLAGzCBNs1-:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ee9648b1cc8e93dea3a854414961b0aad76769fe/tests/Unit/DSC_ScheduledTask.Tests.ps1#L1791)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you also add some additional tests here to verify the changed functionallity?
</blockquote></details>

Done.

**Comment by nickgw** [comment]
@PlagueHO do you mind taking another look at this? I'd love to close this off my list.

**Comment by PlagueHO** [comment]
Cool! Thanks @nickgw - I'll review tonight.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Just some minor tweaks and we can merge!

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-:-NHShs5JBMdkugvUq1mB:b-67s7an)* status: all files reviewed, 3 unresolved discussions (waiting on @nickgw)

___
*[`CHANGELOG.md` line 7 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-N78OggP1GiuzL7-pH-7:-NHSgfs22p1dO4WVGiSl:b-9aokfq) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ee9648b1cc8e93dea3a854414961b0aad76769fe/CHANGELOG.md#L7)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There is an extra f at the beginning of this line.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 1774 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-NHSgno25l4ttKolWv-l:-NHSgno25l4ttKolWv-m:bijnl2e) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/a9e44e23f29de3b427df9bd1099f2f4aa5c409b8/tests/Unit/DSC_ScheduledTask.Tests.ps1#L1774)):*
> ```PowerShell
> 
>             Context 'When a scheduled task is created using a Built In Service Account' {
>                 #
> ```

I think this # can be removed.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 1809 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-NHSguaS3ahAqGuPnmBc:-NHSguaS3ahAqGuPnmBd:b-weijab) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/a9e44e23f29de3b427df9bd1099f2f4aa5c409b8/tests/Unit/DSC_ScheduledTask.Tests.ps1#L1809)):*
> ```PowerShell
>                     }
>                 }
>                 #
> ```

I think this has can be removed.

**Review by nickgw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 7 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-N78OggP1GiuzL7-pH-7:-NHUvImO39Ab4Hs307KQ:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ee9648b1cc8e93dea3a854414961b0aad76769fe/CHANGELOG.md#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

There is an extra f at the beginning of this line.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 1774 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-NHSgno25l4ttKolWv-l:-NHUvILk4NZGw4HeNyZL:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/a9e44e23f29de3b427df9bd1099f2f4aa5c409b8/tests/Unit/DSC_ScheduledTask.Tests.ps1#L1774)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this # can be removed.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 1809 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-NHSguaS3ahAqGuPnmBc:-NHUvHw60rn_L3yTvGtD:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/a9e44e23f29de3b427df9bd1099f2f4aa5c409b8/tests/Unit/DSC_ScheduledTask.Tests.ps1#L1809)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this has can be removed.
</blockquote></details>

Done.



_Code quote:_
```PowerShell
When a scheduled task is created using a Built In Service Accoun
```

**Comment by nickgw** [comment]
@PlagueHO I think I hit all your comments!

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/387#-:-NHY75eVAr99i1DRH8T0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickgw)

**Pull request merged**
