### PR TITLE
Update pipeline files to latest version - Fixes #427

### LINKED ISSUE #427: Update Pipeline Files to Latest DSC Community and Sampler pattern
To fix current build failures need to update the pipeline to use the latest patterns.

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR updates the pipeline and supporting files to the latest DSC Community pattern. It also updates the HQRM VM images to run on windows-latest.

#### This Pull Request (PR) fixes the following issues

- Fixes #427 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).

Remaining N/A

- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428)

### CODE REVIEW

**Comment by johlju** [comment]
The pipeline in the change has enable PSResourceGet, and the compatibility module is not 100% so guessing thats why the integration tests fails. Maybe disable PowerShellGet compatibility module in config [Resolve-Dependency.psd1](https://github.com/dsccommunity/ComputerManagementDsc/pull/428/files#diff-ac003f03430c23f9cca24dc67f251db47302b31fbcb50a9b3aaeeaf650ebc009) and then maybe it is possible to force to load old PowerShellGet for the integration tests?

**Comment by johlju** [comment]
Also, FYI: https://github.com/dsccommunity/ActiveDirectoryCSDsc/pull/144#issuecomment-2143328779

**Comment by johlju** [comment]
> Also, FYI: [dsccommunity/ActiveDirectoryCSDsc#144 (comment)](https://github.com/dsccommunity/ActiveDirectoryCSDsc/pull/144#issuecomment-2143328779)

This has been fixed in a new release.

**Comment by PlagueHO** [comment]
Thanks @johlju - looking at this now and have turned off the PSResourceGet usage.

**Comment by PlagueHO** [comment]
Should be good to review now @johlju  😀

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428)* status: all files reviewed, 5 unresolved discussions (waiting on @PlagueHO)

___
*[`build.yaml` line 21 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNfZI0C0r0MWVT1dM9:-NzNfZI1B1ILOyyf93gd:bxa2qbr) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/build.yaml#L21)):*
> ```YAML
>     - Generate_Markdown_For_Public_Commands
>     - Generate_External_Help_File_For_Public_Commands
>     - Clean_Markdown_Of_Public_Commands
> ```

We can remove these three tasks so they don't run twice. These three tasks are now run by the new meta task `Generate_Wiki_Content` (the original task was refactored into several smaller tasks):
 https://github.com/dsccommunity/DscResource.DocGenerator/blob/b45100769fa1a45b0840831d56dfbdee1ec7a7f3/source/tasks/Generate_Wiki_Content.build.ps1#L87



_Code quote:_
```YAML
    - Generate_Markdown_For_Public_Commands
    - Generate_External_Help_File_For_Public_Commands
    - Clean_Markdown_Of_Public_Commands
```
___
*[`build.yaml` line 26 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNgB7A6nHoTBSa2-o1:-NzNgB7B35Ehi6XlTZ-q:bai4ei3) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/build.yaml#L26)):*
> ```YAML
>     - Package_WikContent
> 
>   pack:
> ```

The `pack` task must run the `docs` metatask to generate the documentation. It can also be run by `build` task, but normally it is not necessary to generate documentation during development,and it takes a while to generate the docs for a larger module, so this has been split up to run in `pack` task, or manually run `docs` task if neede during development. 
___
*[`build.yaml` line 43 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNgpzA2jh3FDsJKV8-:-NzNgpzA2jh3FDsJKV80:b-e0kzii) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/build.yaml#L43)):*
> ```YAML
>     - Create_ChangeLog_GitHub_PR
> 
>   Package_WikContent: |
> ```

This inline task has now been moved to DscResource.DocGenerator so it can be removed here.
___
*[`build.yaml` line 140 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNhwckBaBZAO9ohCZc:-NzNhwckBaBZAO9ohCZd:b-ka4hht) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/build.yaml#L140)):*
> ```YAML
>     TestResult:
>       OutputFormat: NUnitXML
>       OutputEncoding: ascii
> ```

This is the configuration for Pester 5 task in DscResource.Test. This module is still using Pester 4 so maybe we should remove this or keep it and add a comment `# Pester 5 configuration`. Then also add the Pester 4 configuration (althoug it seems the tasks works running with default values):

```
  # Pester 4 configuration
  Script:
    - tests/Unit
  ExcludeTag:
  Tag:
  CodeCoverageOutputFile: JaCoCo_coverage.xml
  CodeCoverageOutputFileEncoding: ascii
  CodeCoverageThreshold: 80
```

Pester 4 configuration and Pester 5 can exist side-by-side - but to actually run Pester 5 tasks all tests need to be converted at the same time.



_Code quote:_
```YAML
  Configuration:
    Run:
      Path:
        - tests/Unit
    Output:
      Verbosity: Detailed
      StackTraceVerbosity: Full
      CIFormat: Auto
    CodeCoverage:
      CoveragePercentTarget: 80
      OutputPath: JaCoCo_coverage.xml
      OutputEncoding: ascii
      UseBreakpoints: false
    TestResult:
      OutputFormat: NUnitXML
      OutputEncoding: ascii
```
___
*[`CHANGELOG.md` line 13 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNjEl926u7y8V1leNJ:-NzNjEl926u7y8V1leNK:btfvyyf) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/CHANGELOG.md#L13)):*
> ```Markdown
>   - Updated pipeline files to match current DSC Community patterns - fixes [Issue #427](https://github.com/dsccommunity/ComputerManagementDsc/issues/427).
>   - Updated HQRM step to use windows-latest image.
>   - Update pipeline to use `PublishCodeCoverageResults@2` task to publish code coverage results.
> ```

We can keep it, but please note that v2 does ot have all the functionality as v1 and the team has not said they will retire v1. See comments in PR: https://github.com/dsccommunity/SqlServerDsc/pull/2025
___
*[`Resolve-Dependency.psd1` line 11 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNkF1gCtfJdTulFUdU:-NzNkF1h4DbAIi0pXqBE:bv75l2t) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/Resolve-Dependency.psd1#L11)):*
> ```PowerShell
> 
>     # Setting to $true currenly (2024-06-02) causes integration test failures
>     UsePSResourceGet = $false
> ```

FYI. It is still possible to still use PSResourceGet (or the even faster ModuleFast) manually from command line with the build script by using `-UsePSResourceGet` or `-UseModuleFast` together with `-ResolveDepencency`. It helps to get dependencies faster in the dev cycle.
___
*[`.vscode/analyzersettings.psd1` line 4 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNlHKf5SNLMwcOC067:-NzNlHKf5SNLMwcOC068:bc1fa51) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/.vscode/analyzersettings.psd1#L4)):*
> ```PowerShell
>     CustomRulePath      = @(
>         './output/RequiredModules/DscResource.AnalyzerRules'
>         './tests/QA/AnalyzerRules/SqlServerDsc.AnalyzerRules.psm1'
> ```

THis can be remove, it is specific SqlServerDsc rules for that specific module.

**Review by PlagueHO — COMMENTED** [review]
Should be good to go once build passes. Thanks @johlju 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-:-NzPUdim16_V8jSo7du5:b-3j7a9q)* status: 6 of 10 files reviewed, 5 unresolved discussions (waiting on @johlju)

___
*[`build.yaml` line 21 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNfZI0C0r0MWVT1dM9:-NzPOaWMAGGLDZNVmzDa:b-pfk84u) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/build.yaml#L21)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove these three tasks so they don't run twice. These three tasks are now run by the new meta task `Generate_Wiki_Content` (the original task was refactored into several smaller tasks):
 https://github.com/dsccommunity/DscResource.DocGenerator/blob/b45100769fa1a45b0840831d56dfbdee1ec7a7f3/source/tasks/Generate_Wiki_Content.build.ps1#L87
</blockquote></details>

Done! And repeated in NetworkingDsc and StorageDsc - thanks for info!
___
*[`build.yaml` line 26 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNgB7A6nHoTBSa2-o1:-NzPP0Ok3_ffAMNdSNSq:but2gbo) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/build.yaml#L26)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The `pack` task must run the `docs` metatask to generate the documentation. It can also be run by `build` task, but normally it is not necessary to generate documentation during development,and it takes a while to generate the docs for a larger module, so this has been split up to run in `pack` task, or manually run `docs` task if neede during development.
</blockquote></details>

Done! Added docs task to pack. And repeated in NetworkingDsc and StorageDsc - thanks for info!
___
*[`build.yaml` line 43 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNgpzA2jh3FDsJKV8-:-NzPPK4sEvjayxoNLkWU:b-fttv00) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/build.yaml#L43)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This inline task has now been moved to DscResource.DocGenerator so it can be removed here.
</blockquote></details>

Done. Removed block and corrected task name (had a misspelling that prevented it from working). And repeated in NetworkingDsc and StorageDsc - thanks for info!
___
*[`build.yaml` line 140 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNhwckBaBZAO9ohCZc:-NzPQMlT5QnY7ZVDoVWi:b-6p69c8) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/build.yaml#L140)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This is the configuration for Pester 5 task in DscResource.Test. This module is still using Pester 4 so maybe we should remove this or keep it and add a comment `# Pester 5 configuration`. Then also add the Pester 4 configuration (althoug it seems the tasks works running with default values):

```
  # Pester 4 configuration
  Script:
    - tests/Unit
  ExcludeTag:
  Tag:
  CodeCoverageOutputFile: JaCoCo_coverage.xml
  CodeCoverageOutputFileEncoding: ascii
  CodeCoverageThreshold: 80
```

Pester 4 configuration and Pester 5 can exist side-by-side - but to actually run Pester 5 tasks all tests need to be converted at the same time.
</blockquote></details>

Done. Have left V5 config in place, but added v4 config. And repeated in NetworkingDsc and StorageDsc - thanks for info!
___
*[`CHANGELOG.md` line 13 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNjEl926u7y8V1leNJ:-NzPRPlyBDaPJ8oPFDp4:bulcxri) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/CHANGELOG.md#L13)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can keep it, but please note that v2 does ot have all the functionality as v1 and the team has not said they will retire v1. See comments in PR: https://github.com/dsccommunity/SqlServerDsc/pull/2025
</blockquote></details>

Done. Moved back for v1 task.
___
*[`Resolve-Dependency.psd1` line 11 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNkF1gCtfJdTulFUdU:-NzPQgLQ7BzOFnoCWjCu:b-w7bchl) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/Resolve-Dependency.psd1#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

FYI. It is still possible to still use PSResourceGet (or the even faster ModuleFast) manually from command line with the build script by using `-UsePSResourceGet` or `-UseModuleFast` together with `-ResolveDepencency`. It helps to get dependencies faster in the dev cycle.
</blockquote></details>

Cool! Thanks for tip!
___
*[`.vscode/analyzersettings.psd1` line 4 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzNlHKf5SNLMwcOC067:-NzPRALdD_E6k1rZ6tay:b-kske58) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/b23219a2ee8bd6720c635c81677bbd22b2091dcb/.vscode/analyzersettings.psd1#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

THis can be remove, it is specific SqlServerDsc rules for that specific module.
</blockquote></details>

Done! Oops- thought I'd checked for any remaining SQLServerDsc stuff - missed this :cry:

**Review by johlju — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

___
*[`RequiredModules.psd1` line 24 at r5](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-NzbOpTtCnfGU9h6R8b6:-NzbOpTtCnfGU9h6R8b7:b-54425t) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/52669cd07cc94ba79473e6e420ae3bdd09a6653d/RequiredModules.psd1#L24)):*
> ```PowerShell
> 
>     # Build dependencies needed for using the module
>     'DscResource.Common'           = 'latest'
> ```

Nit: we got a couple of extra spaces here, fix it if you like, or merge as is. :slightly_smiling_face:

**Review by PlagueHO — COMMENTED** [review]
Thanks @johlju ! Have corrected spacing.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428#-:-NzjAamo06qNOI0eQ3QZ:bri4od9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Pull request merged**
