### PR TITLE
ComputerManagementDsc: Remove resource named from module manifest in `source`

### LINKED ISSUE #396: ComputerManagementDsc: Remove resource named from module manifest in `source`
Currently the DSC resource names are present for the property `DscResourcesToExport` in the module manifest in the `source` folder. 
https://github.com/dsccommunity/ComputerManagementDsc/blob/438d2c29a938f1c4e2b5a1e916bd6205fd950c13/source/ComputerManagementDsc.psd1#L39

This is no longer necessary as the pipeline updates this property automatically with both MOF- and class-based resource names.

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- ComputerManagementDsc
  - The resource names was removed from the property `DscResourcesToExport`
    in the module manifest in the source folder since the built module is
    automatically updated with this information by the pipeline. Fixes [Issue #396](https://github.com/dsccommunity/ComputerManagementDsc/issues/396).

#### This Pull Request (PR) fixes the following issues

- Fixes #396

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/397)

### CODE REVIEW

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/397)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`CHANGELOG.md` line 17 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/397#-NG8KcOMBpuE4x0uv88V:-NG8KcOMBpuE4x0uv88W:b-oh5o2j) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/1ccd11a0f15a43c8202bd0d0d27157295b5ceff5/CHANGELOG.md#L17)):*
> ```Markdown
> 
> - ComputerManagementDsc
>   - The resource names was removed from the property `DscResourcesToExport`
> ```

Nitpick:



_Suggestion:_
```Markdown
  - The resource names were removed from the property `DscResourcesToExport`
    in the module manifest in the source folder as the built module is
    automatically updated with this information by the pipeline - Fixes [Issue #396](https://github.com/dsccommunity/ComputerManagementDsc/issues/396).
```

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/397)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 17 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/397#-NG8KcOMBpuE4x0uv88V:-NGAzC0G2eMGFQH6bpfw:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/1ccd11a0f15a43c8202bd0d0d27157295b5ceff5/CHANGELOG.md#L17)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick:
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/397)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Review by PlagueHO — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/397#-:-NGFRWtLCo_3ikQefmY9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
