### PR TITLE
Fix WindowsEventLog: Evaluation of event log differ

### LINKED ISSUE #229: WindowsEventLog: Evaluation of event log differ
The existence of the event log name is evaluated twice in this code, this is redundant and should be only evaluated once. Also, the two evaluation differ in that one uses `-like` and the other uses `-eq`, this should probably only be either one, not both.

https://github.com/PowerShell/ComputerManagementDsc/blob/75152fc76595b7c36ce6e18439d7488a2df0c0d0/DSCResources/MSFT_WindowsEventLog/MSFT_WindowsEventLog.psm1#L180-L184

### PR DESCRIPTION
**Pull request by Outek**
#### Pull Request (PR) description

Fix WindowsEventLog: Evaluation of event log differ

#### This Pull Request (PR) fixes the following issues
    - Fixes #229 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/277)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @Outek - you might need to rebase your branch as this PR includes a bunch of changes that have already been merged to dev. Although this doesn't have merge conflicts the instructions are still valid: https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by PlagueHO** [comment]
@Outek - Oh wait - I updated the branch and it corrected it. So all good. Sorry about that.

**Comment by PlagueHO** [comment]
Hi @Outek - looks like you've got some trailing spaces in the MD: https://ci.appveyor.com/project/PowerShell/computermanagementdsc/builds/27898015?fullLog=true#L1083

**Comment by Outek** [comment]
Hi @PlagueHO 
Is here something wrong with the MR?

**Pull request closed without merging**
