### PR TITLE
Add new resource IEEnhancedSecurityConfiguration

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
This moves the resource xIEEsc from module xSystemSecurity and renames it to IEEnhancedSecurityConfiguration.

#### This Pull Request (PR) fixes the following issues
- part of issue https://github.com/PowerShell/DscResources/issues/374

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/303)

### CODE REVIEW

**Comment by johlju** [comment]
I will fix up this PR to the new pattern,

**Comment by PlagueHO** [comment]
@johlju - looks like this has some conflicts.

**Comment by johlju** [comment]
Yep. Give me a few minutes to rebase and fix up the tests with the new pattern. 😄

**Comment by johlju** [comment]
Hmm.. the rebase removed the integration tests. :/ The files are just poof gone. Strange. I get them from the fork branch. It will take another few minutes. 😄

**Comment by johlju** [comment]
@PlagueHO Now it is ready. It was to early in the morning, I forgot to fetch latest changes from fork before rebasing so files disappeared 🤦‍♂ Ready for review now!

**Comment by PlagueHO** [comment]
Sweet - just in bed now, but will review tomorrow first thing!

**Pull request merged**
