### PR TITLE
Set registry item type explicitly on various resources

### LINKED ISSUE #433: IEEnhancedSecurityConfiguration never in desired state when Enabled is set to False
### Problem description

When disabling IE Enhanced Security, the desired state is always False.

In case the LCM is configured with 'RebootNodeIfNeeded = $true' and 'ActionAfterReboot = ContinueConfiguration', a reboot loop is happening.

### Verbose logs

```text
2024-08-30T18:51:29.160+00:00 verbose [MYCOMPUTER]: LCM:  [ Start  Test     ]  [[IEEnhancedSecurityConfiguration]DisableForAdministrators]
2024-08-30T18:51:29.160+00:00 verbose [MYCOMPUTER]:                            [[IEEnhancedSecurityConfiguration]DisableForAdministrators] Importing the module DSC_IEEnhancedSecurityConfiguration in force mode.
2024-08-30T18:51:29.253+00:00 verbose [MYCOMPUTER]:                            [[IEEnhancedSecurityConfiguration]DisableForAdministrators] Testing IE Enhanced Security Configuration state for 'Administrators'. (IEESC0003)
2024-08-30T18:51:29.253+00:00 verbose [MYCOMPUTER]:                            [[IEEnhancedSecurityConfiguration]DisableForAdministrators] Getting IE Enhanced Security Configuration state for 'Administrators'. (IEESC0001)
2024-08-30T18:51:29.285+00:00 verbose [MYCOMPUTER]:                            [[IEEnhancedSecurityConfiguration]DisableForAdministrators] The IE Enhanced Security Configuration for 'Administrators' was enabled, but expected it to be disabled. (IEESC0006)
2024-08-30T18:51:29.285+00:00 verbose [MYCOMPUTER]: LCM:  [ End    Test     ]  [[IEEnhancedSecurityConfiguration]DisableForAdministrators]  in 0.1250 seconds.
2024-08-30T18:51:29.285+00:00 verbose [MYCOMPUTER]: LCM:  [ Start  Set      ]  [[IEEnhancedSecurityConfiguration]DisableForAdministrators]
2024-08-30T18:51:29.285+00:00 verbose [MYCOMPUTER]:                            [[IEEnhancedSecurityConfiguration]DisableForAdministrators] Importing the module DSC_IEEnhancedSecurityConfiguration in force mode.
2024-08-30T18:51:29.394+00:00 verbose [MYCOMPUTER]:                            [[IEEnhancedSecurityConfiguration]DisableForAdministrators] Getting IE Enhanced Security Configuration state for 'Administrators'. (IEESC0001)
2024-08-30T18:51:29.410+00:00 verbose [MYCOMPUTER]:                            [[IEEnhancedSecurityConfiguration]DisableForAdministrators] Setting IE Enhanced Security Configuration state for 'Administrators'. (IEESC0002)
2024-08-30T18:51:29.410+00:00 verbose [MYCOMPUTER]: LCM:  [ End    Set      ]  [[IEEnhancedSecurityConfiguration]DisableForAdministrators]  in 0.1250 seconds.
```

### DSC configuration

```powershell
IEEnhancedSecurityConfiguration DisableForAdministrators
{
  Role            = 'Administrators'
  Enabled         = $false
}
```

### Suggested solution

When running the following command:

```powershell
Invoke-DscResource -Name IEEnhancedSecurityConfiguration -Method Get -ModuleName ComputerManagementDsc -Property @{ Role = 'Administrators'; Enabled = $false } -Verbose
```

The result is True (which is not correct):

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceGet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer AIS02TESTSQL with user sid S-1-5-21-3403967775-1204755894-2229100015-82601.
VERBOSE: [AIS02TESTSQL]:                            [DSCEngine] Importing the module C:\Program Files\WindowsPowerShell\Modules\ComputerManagementDsc\9.1.0\DscResources\DSC_IEEnhancedSecurityConfiguration\DSC_IEEnhancedSecurityConfiguration.psm1 in force mode.
VERBOSE: [AIS02TESTSQL]:                            [[IEEnhancedSecurityConfiguration]DirectResourceAccess] Importing the module DSC_IEEnhancedSecurityConfiguration in force mode.
VERBOSE: [AIS02TESTSQL]:                            [[IEEnhancedSecurityConfiguration]DirectResourceAccess] Getting IE Enhanced Security Configuration state for 'Administrators'. (IEESC0001)
VERBOSE: [AIS02TESTSQL]: LCM:  [ End    Get      ]  [[IEEnhancedSecurityConfiguration]DirectResourceAccess]  in 0.0940 seconds.
VERBOSE: [AIS02TESTSQL]: LCM:  [ End    Set      ]    in  11.8180 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.

ConfigurationName    :
DependsOn            :
ModuleName           : ComputerManagementDsc
ModuleVersion        : 9.1.0
PsDscRunAsCredential :
ResourceId           :
SourceInfo           :
Enabled              : True
Role                 : Administrators
SuppressRestart      : False
PSComputerName       : localhost

VERBOSE: Time taken for configuration job to complete is 12.065 seconds

Looking at the source code, the following registry value is checked:

```powershell
PS C:\Windows\system32> (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}').IsInstalled
```
False

Which is different from the Invoke-DscResource command.

The root cause seems to be the cast to boolean, which returns true, even when the registry value is false:

```powershell
PS C:\Windows\system32> [bool](Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}').IsInstalled
```
True

Proposed solution:

Change in Get-TargetResource

`$currentlyEnabled = [System.Boolean] (Get-ItemProperty -Path $registryKey -ErrorAction 'Stop').$script:registryKey_Property`

To

`$currentlyEnabled = (Get-ItemProperty -Path $registryKey -ErrorAction 'Stop').$script:registryKey_Property -eq 'True'`

### Operating system the target node is running

```text
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version and build the target node is running

```text
Name                           Value
----                           -----
PSVersion                      5.1.17763.6189
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.6189
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### ComputerManagementDsc version

```text
Name                  Version Path
----                  ------- ----
ComputerManagementDsc 9.1.0   C:\Program Files\WindowsPowerShell\Modules\ComputerManagementDsc\9.1.0\ComputerManagementDsc.psd1
```

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description

There's an issue with Set-ItemProperty which we've encountered before (#412) where Set-ItemProperty has undefined behaviour when setting a registry value without the 'Type' specified.

On some systems, it defaults to String - on others DWord
https://stackoverflow.com/questions/16787365/set-itemproperty-sets-registry-value-as-string-on-some-systems-instead-of-dword

This pull specifically defines the Type of the registry value to set in all instances of Set-ItemProperty in the module.

#### This Pull Request (PR) fixes the following issues

- Fixes #433 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/438)

### CODE REVIEW

**Comment by Borgquite** [comment]
Looks like you can't splat with Type = DWord - otherwise you get

`System.Management.Automation.CommandNotFoundException: The term 'DWord' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

Trying to set manually

**Comment by dan-hughes** [comment]
> Looks like you can't splat with Type = DWord - otherwise you get
> 
> `System.Management.Automation.CommandNotFoundException: The term 'DWord' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
> 
> Trying to set manually

Type is a Enum. In a splat it should work if you put the value is quotes e.g. 'DWord'

**Comment by Borgquite** [comment]
> Type is a Enum. In a splat it should work if you put the value is quotes e.g. 'DWord'

Ah, thanks. I'll give that a go now.

**Review by kilasuit — APPROVED** [review]

**Review by dan-hughes — COMMENTED** [review]
Just a couple of things.

> Reviewed 5 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/438#-:-O9nqJzV0lFttvfJT77K:b-kj01gu)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @Borgquite)

___
*[`source/DSCResources/DSC_RemoteDesktopAdmin/DSC_RemoteDesktopAdmin.psm1` line 180 at r2](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/438#-O9nq-ka9bHgpjMklzJx:-O9nq-ka9bHgpjMklzJy:beppfhs) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/a3758daee880c453288bf07d0c8ae012c11e241a/source/DSCResources/DSC_RemoteDesktopAdmin/DSC_RemoteDesktopAdmin.psm1#L180)):*
> ```PowerShell
>     {
>         Write-Verbose -Message ($script:localizedData.SettingUserAuthenticationMessage -f $UserAuthentication)
>         Set-ItemProperty -Path $script:winStationsRegistryKey -Name "UserAuthentication" -Value $UserAuthenticationRegistry -Type DWord
> ```

Can this be changed to use a splat to reduce line length.
___
*[`source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1` line 902 at r2](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/438#-O9nq8auDoCs_E98BvWb:-O9nq8auDoCs_E98BvWc:b-yqr8vp) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/a3758daee880c453288bf07d0c8ae012c11e241a/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L902)):*
> ```PowerShell
>     try
>     {
>         Set-ItemProperty -Path $logRegistryPath `
> ```

Same again, it also removes the horrible backticks
___
*[`tests/Integration/DSC_PendingReboot.Tests.ps1` line 62 at r2](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/438#-O9nqEgR8mGKDXF79WYa:-O9nqEgR8mGKDXF79WYb:b-3ahcot) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/a3758daee880c453288bf07d0c8ae012c11e241a/tests/Integration/DSC_PendingReboot.Tests.ps1#L62)):*
> ```PowerShell
>     if ($script:currentPendingFileRenameState)
>     {
>         $null = Set-ItemProperty `
> ```

Same again.

**Review by Borgquite — COMMENTED** [review]
All done!

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/438#-:-O9nwnWI9wLnuw0-Dvt3:b-cw6y1x)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @dan-hughes)

___
*[`source/DSCResources/DSC_RemoteDesktopAdmin/DSC_RemoteDesktopAdmin.psm1` line 180 at r2](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/438#-O9nq-ka9bHgpjMklzJx:-O9nwln30ta-HU07tkPE:b-896fix) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/a3758daee880c453288bf07d0c8ae012c11e241a/source/DSCResources/DSC_RemoteDesktopAdmin/DSC_RemoteDesktopAdmin.psm1#L180)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Can this be changed to use a splat to reduce line length.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1` line 902 at r2](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/438#-O9nq8auDoCs_E98BvWb:-O9nwmAO761xd5Q6VOFw:b-896fix) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/a3758daee880c453288bf07d0c8ae012c11e241a/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L902)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Same again, it also removes the horrible backticks
</blockquote></details>

Done.
___
*[`tests/Integration/DSC_PendingReboot.Tests.ps1` line 62 at r2](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/438#-O9nqEgR8mGKDXF79WYa:-O9nwmdm7HR31IYSUSz2:b-896fix) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/a3758daee880c453288bf07d0c8ae012c11e241a/tests/Integration/DSC_PendingReboot.Tests.ps1#L62)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Same again.
</blockquote></details>

Done.

**Review by dan-hughes — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/438#-:-O9o37iC58JMmuK4BObo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Borgquite)

**Pull request merged**
