### PR TITLE
ScheduledTask: Removing helper function Disable-ScheduledTask

### LINKED ISSUE #137: xScheduledTask can't disable default ScheduledDefrag task
I'm using xComputerManagement 3.2.0.0, attempting to disable the default task **ScheduledDefrag**

I've tried populating all of the current values for the task, only changing **Enable** to $false and **ScheduleType** to 'Once'.

Here is the configuration and error thrown:

```        xScheduledTask DisableScheduledDefragTask
        {
            ActionArguments                 = '-c -h -k -g -$'
            ActionExecutable                = '%windir%\system32\defrag.exe'
            AllowStartIfOnBatteries         = $false
            Compatibility                   = 'Win8'
            Description                     = 'This task optimizes local storage drives.'
            DisallowDemandStart             = $false
            DisallowHardTerminate           = $false
            DisallowStartOnRemoteAppSession = $false
            DontStopIfGoingOnBatteries      = $false
            DontStopOnIdleEnd               = $false
            Enable                          = $false
            Ensure                          = 'Present'
            ExecutionTimeLimit              = '3.00:00:00'
            Hidden                          = $false
            IdleDuration                    = '00:00:00'
            IdleWaitTimeout                 = '00:00:00'
            LogonType                       = 'ServiceAccount'
            MultipleInstances               = 'IgnoreNew'
            Priority                        = '7'
            RandomDelay                     = '00:00:00'
            RepeatInterval                  = '00:00:00'
            RepetitionDuration              = 'Indefinitely'
            RestartCount                    = '0'
            RestartInterval                 = '00:00:00'
            RestartOnIdle                   = $false
            RunLevel                        = 'Highest'
            RunOnlyIfIdle                   = $false
            RunOnlyIfNetworkAvailable       = $false
            ScheduleType                    = 'Once'
            StartTime                       = '1/28/2018 12:00:00 AM'
            TaskName                        = 'ScheduledDefrag'
            TaskPath                        = '\Microsoft\Windows\Defrag\'
            User = 'SYSTEM'
            WakeToRun                       = $false
        }


VERBOSE: [ADM3]: LCM:  [ End    Test     ]  [[xScheduledTask]DisableScheduledDefragTask]  in 0.4430 seconds.
PowerShell DSC resource MSFT_xScheduledTask  failed to execute Test-TargetResource functionality with error message: Trigger type  not recognized.
Parameter name: CimClassName
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost```

### PR DESCRIPTION
**Pull request by EDockus**
#### Task list

- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md in the resource folder.
- [X] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/228)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @EDockus - I'll review this once the tests are passing. Looks like there are some long lines in the CHANGELOG.MD: Lines 6/7: https://ci.appveyor.com/project/PowerShell/computermanagementdsc/builds/25584560?fullLog=true#L813

Suggest using Visual Studio Code and adding the [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) extension - it'll highlight any lines that violate markdown rules.

**Comment by PlagueHO** [comment]
Can you rebase this one @EDockus to resolve conflicts and we'll work on getting it through.

**Comment by EDockus** [comment]
> Can you rebase this one @EDockus to resolve conflicts and we'll work on getting it through.

Hi, I've done that now. I'm not exactly sure how to update the unit tests, I assumed those particular ones were no longer needed as functionality was moved off the helper function onto the built-in function which has it's own tests.

**Comment by PlagueHO** [comment]
Hi @EDockus - sorry about this, but I missed your comments. I'll take a look at the current state and advise what needs to be done. Can you resolve the conflicts?

**Comment by EDockus** [comment]
> Hi @EDockus - sorry about this, but I missed your comments. I'll take a look at the current state and advise what needs to be done. Can you resolve the conflicts?

No worries @PlagueHO. Conflicts now resolved.

**Comment by PlagueHO** [comment]
Sorry @EDockus - more conflicts. Can you fix and I'll try and get this merged ASAP! Sorry about that.

**Comment by PlagueHO** [comment]
Hi @EDockus - sorry about the delay on this one - are you still working on it?

**Pull request closed without merging**
