### PR TITLE
SystemProtection/SystemRestorePoint: New DSC Resources

### LINKED ISSUE #364: Merge xWindowsRestore into ComputerManagementDsc
### Description
I want to configure System Restores for new Windows 10 machines and this module doesn't have those resources available, but I did find an old PowerShell module (xWindowsRestore) that @gaelcolas and the PowerShell Team wrote back in 2014.  Rather than having a one-off module just handling system restores, I'd like to merge that module into ComputerManagementDsc with all the Pester testing and other dsccommunity goodies.

The other interesting note is that when you click the Project Site link in the gallery for xWIndowsRestore, it jumps to a generic "browse code samples" webpage rather than a git-style site or other site with specifics on the module itself.

### Proposed properties
Keep the current code as-is and merge into this module.

### Special considerations or limitations
The addition of unit and integration tests would really be the only change to the module itself.

### PR DESCRIPTION
**Pull request by cohdjn**
#### Pull Request (PR) description
Add new resources SystemProtection and SystemRestorePoint.

#### This Pull Request (PR) fixes the following issues
- Fixes #364 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/373)

### CODE REVIEW

**Comment by cohdjn** [comment]
A couple of notes on the Pester tests since code coverage is failing...

There are no integration tests because this is designed to work against workstations and not servers.  I couldn't figure out a reasonable way to implement them.  If you have ideas, I'm all ears!

On the unit tests, there are large portions of the tests that are only run when Pester is on a workstation.  You'll see in the scripts that I'm querying the product code and bypassing a lot them for that reason.  I've run the unit tests on my Windows 10 workstation and they all pass.

**Comment by cohdjn** [comment]
I made a minor correction to the Pester tests and it looks like something went wrong with integration tests on the last pipeline build.  I don't have any integration tests so there's something else going on there.

**Comment by cohdjn** [comment]
@PlagueHO I know you're busy.... wanted to see if you have some time to work this through with me?

**Comment by PlagueHO** [comment]
Hi @cohdjn - sorry about the delay. I'll get onto the review this week and see if we can increase code coverage.

**Comment by PlagueHO** [comment]
HI @cohdjn - the main issue with the test coverage is that the unit tests will only cover the code that operates on the OS that the tests are run on. Unit tests shouldn't really (ideally 😀 ) behave this way. We'd instead design tests that mocked the behavior of each OS and ran them on each.

I think this is actually quite simple to fix here (famous last words).

Example:
This block only runs _if_ we're running tests on a desktop OS - so we'll never get these running in the Azure DevOps pipelines (which only use Server OS):
https://github.com/cohdjn/ComputerManagementDsc/blob/main/tests/Unit/DSC_SystemRestorePoint.Tests.ps1#L96

This block also only sets up certain variables/mocks etc if it is a desktop OS: 
https://github.com/cohdjn/ComputerManagementDsc/blob/main/tests/Unit/DSC_SystemRestorePoint.Tests.ps1#L59

However, we've got some code that sets up mocks and other test fixtures that is dependent on classes that only exist on the desktop OS: 
```powershell
            $srClass = New-Object -TypeName System.Management.ManagementClass `
                -ArgumentList ('root\default', 'SystemRestore', $null)

            $getComputerRestorePoint = New-Object -TypeName System.Management.ManagementObject
            $getComputerRestorePoint = $srClass.CreateInstance()

            $getComputerRestorePoint.Description      = 'DSC Unit Test'
            $getComputerRestorePoint.SequenceNumber   = 1
            $getComputerRestorePoint.RestorePointType = 12
```

To solve this you wouldn't rely on the actual class, you'd create a fake/mock for the object:
```powershell
            $getComputerRestorePoint = New-Object PSObject
            $getComputerRestorePoint = Add-Member -MemberType NoteProperty -Name Description -Value 'DSC Unit Test'
            $getComputerRestorePoint = Add-Member -MemberType NoteProperty -Name SequenceNumber -Value 1
            $getComputerRestorePoint = Add-Member -MemberType NoteProperty -Name RestorePointType -Value 12
```

This object isn't the same type (System.Management.ManagementObject), but as long as the code in the resource doesn't check it or call specific methods on the object.

The next problem is that anywhere there is a `if ($productType -eq 1)` indicates a problem. For example, change:

```powershell
        if ($productType -eq 1)
        {
            $srClass = New-Object -TypeName System.Management.ManagementClass `
                -ArgumentList ('root\default', 'SystemRestore', $null)

            $getComputerRestorePoint = New-Object -TypeName System.Management.ManagementObject
            $getComputerRestorePoint = $srClass.CreateInstance()

            $getComputerRestorePoint.Description      = 'DSC Unit Test'
            $getComputerRestorePoint.SequenceNumber   = 1
            $getComputerRestorePoint.RestorePointType = 12
        }
```
to 
```powershell
            $getComputerRestorePoint = New-Object PSObject
            $getComputerRestorePoint = Add-Member -MemberType NoteProperty -Name Description -Value 'DSC Unit Test'
            $getComputerRestorePoint = Add-Member -MemberType NoteProperty -Name SequenceNumber -Value 1
            $getComputerRestorePoint = Add-Member -MemberType NoteProperty -Name RestorePointType -Value 12
```

We also need to run tests on both the path followed when run on a desktop OS and when run on a Server OS. So we need to change the describe block for each `*-TargetResource` to run each path regardless of OS:

```powershell
Describe 'DSC_SystemRestorePoint\Get-TargetResource' -Tag 'Get' {
    Context 'When running on a workstation OS' {
        Context 'When getting the target resource' {
                    It 'Should return Absent when requested restore point does not exist' {
                        Mock -CommandName Get-ComputerRestorePoint -MockWith { return $getComputerRestorePoint }
                        Mock -CommandName Get-CimInstance @workstationMock

                        $result = Get-TargetResource -Ensure 'Present' -Description 'Does Not Exist'

                        $result | Should -BeOfType Hashtable
                        $result.Ensure | Should -Be 'Absent'
                    }

                    It 'Should return present when requested restore point exists' {
                        Mock -CommandName Get-ComputerRestorePoint -MockWith { return $getComputerRestorePoint }
                        Mock -CommandName Get-CimInstance @workstationMock

                        $result = Get-TargetResource -Ensure 'Present' -Description 'DSC Unit Test'

                        $result | Should -BeOfType Hashtable
                        $result.Ensure | Should -Be 'Present'
                    }
        }
    }

    Context 'When running on a server OS' {
        Context 'When getting the target resource' {
                It 'Should return Absent and write a warning on a server operating system' {
                    Mock -CommandName Write-Warning

                   # There is a gap in testing here - we need to validate that Get-ComputerRestorePoint is NOT called (need a mock and an assert).
                    Mock -CommandName Get-CimInstance @serverMock

                    $protectionSettings = Get-TargetResource -Ensure 'Present' -Description 'DSC Unit Test'

                    $protectionSettings.Ensure | Should -Be 'Absent'
                    Assert-MockCalled -CommandName Write-Warning -Times 1
                }
        }
    }
```

Fundamentally, if you can change the tests like the above then it will increase the coverage to allow the PR to be merged - because at the moment we're not really testing the most important code (when run on desktop).

Note: sometimes it can be fairly difficult to mock objects that don't exist (especially where we need to call methods), in which case we need to wrap this code in smaller helper functions and mock those instead. But we can deal with that if encountered.

DSC was never really designed with desktop OS's in mind (e.g. OS drift is pretty normal because of users and we had GPO to deal with a lot of stuff) - so we are going to have to do a lot more work to mock elements of the OS.

Does that make sense?

Happy to run through additional issues/blockers as the come back?

**Comment by johlju** [comment]
@cohdjn when you have time can you resolve the merge conflicts, and then I think we can merge this one as it does not break or change any existing resources. 🤔

**Comment by johlju** [comment]
@cohdjn can you look at the failing tests? We need those to pass before we can merge. 🙂

**Comment by cohdjn** [comment]
I believe I have all of the issues I can fix handled.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 15 of 21 files at r1, 1 of 3 files at r3, 2 of 3 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/373)* status: all files reviewed, 1 unresolved discussion (waiting on @cohdjn and @PlagueHO)

___
*[`CHANGELOG.md` line 129 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/373#-OAN68XiANSyE3gKt2Jm:-OAN68XiANSyE3gKt2Jn:byevbpn) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/2a63db2ba7b5e81a29967a9fa717a80c785ad758/CHANGELOG.md#L129)):*
> ```Markdown
> 
> - SystemProtection
>   - New resource to configure System Protection settings (formerly xWindowsRestore) - Fixes [Issue #364](https://github.com/dsccommunity/ComputerManagementDsc/issues/364).
> ```

Need to move the changelog entries to the Unreleased section. This happens when there is a release before merging a PR, conflict resoultion does not understand that the Unreleased section "moved".

**Comment by johlju** [comment]
@cohdjn just a tiny change then I suggest we merge this.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/373#-:-OAT7UC33D2daD1heGMw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Pull request merged**
