### PR TITLE
ScheduledTask: Resolved inconsistent treatment of BuiltInAccount property.

### PR DESCRIPTION
**Pull request by wm-wilson**
#### Pull Request (PR) description
Fixed inconsistent treatment of the BuiltInAccount property for the ScheduledTask resource.
The Set method prefixes the "SYSTEM", "LOCAL SERVICE", "NETWORK SERVICE" account names with the "NT Authority\" domain.
This results in a scheduled task that runs, but the DSC resource test will always fail on the BuiltInAccount property check. For example:
Expected = 'SYSTEM'
Actual = 'NT Authority\SYSTEM.'

Added integration test cases for the ServiceAccount Logontype/BuiltInAccount property, demonstrating the above.

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/313)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @wm-wilson - thanks for submitting this! Great submission. It looks like the tests are failing. Can you take a look at this?

**Comment by wm-wilson** [comment]
@PlagueHO - sorry about that, fixed the unit test to match the current observed behaviour from Get-ScheduledTask.

**Comment by wm-wilson** [comment]
Apologies if I've missed some protocol here. I submitted the test fix 12 days ago but the pull request is still labelled as "waiting for codefix". Is there something else I need to do to indicate that this is ready for further review?

**Comment by PlagueHO** [comment]
Hi @wm-wilson - sorry about the delay. It is waiting on me to complete the review. I'll get onto this over the weekend. Been a bit snowed under with projects.

**Comment by wm-wilson** [comment]
@PlagueHO - Hopefully I got that right.

No worries re. the delay - I suspect we've all got lots of plates spinning right now!

**Comment by wm-wilson** [comment]
PEBKAC

**Comment by wm-wilson** [comment]
Changelog corrected. Thanks!

**Comment by wm-wilson** [comment]
Done!

**Pull request merged**
