### PR TITLE
Fix PendingReboot Localized Data issue - Fixes #350

### LINKED ISSUE #350: [PendingReboot] DSC_PendingReboot.data.psd1 can't be found in Resource Folder
#### Details of the scenario you tried and the problem that is occurring

I'm using the the DSC_PendingReboot Resource in some configurations. When I tried to apply one configuration on a german ISO I get the Message which I paste in the Verbose logs.
**Mention:** Not only on a German OS but on another Machine with another ISO he looked for [...]ComputerManagementDsc\8.4.0\DscResources\DSC_PendingReboot\**en-GB**
He tries to find the DSC_PendingReboot.data.psd1 in the "C:\ProgramFiles\WindowsPowerShell\Modules\ComputerManagementDsc\8.4.0\DscResources\DSC_PendingReboot\de-DE" Path

**Translation of the verbose logs:** Import of Module DSC_PendingReboot failed with error the Windows PowerShell datafile DSC_PendingReboot.data.psd1 cant be found in Path "C:\ProgramFiles\WindowsPowerShell\Modules\ComputerManagementDsc\8.4.0\DscResources\DSC_PendingReboot\de-DE\" or in a higher Directory.

#### Verbose logs showing the problem

PS C:\> Start-DscConfiguration -UseExisting -Wait -Verbose
AUSFÜHRLICH: Vorgang "CIM-Methode aufrufen" mit den folgenden Parametern durchführen, "'methodName' = ApplyConfiguration,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration".                                                                                                                                                                      
AUSFÜHRLICH: Vom Computer 'DESKTOP-XXXXXXX' mit Benutzer-SID 'MySID' ist ein LCM-Methodenaufruf eingegangen.                                                                   
AUSFÜHRLICH: [DESKTOP-XXXXXXX]:                            [] Das Konsistenzmodul wird gestartet.                                                                                                                       
AUSFÜHRLICH: [DESKTOP-XXXXXXX]:                            [] Eine ausstehende Konfiguration ist vorhanden. Von DSC wird eine SET-Anforderung für die ausstehende Konfiguration verarbeitet.                            
AUSFÜHRLICH: [DESKTOP-XXXXXXX]:                            [] Die Konsistenzprüfung ist abgeschlossen.                                                                                                                  
Importieren des Moduls DSC_PendingReboot mit Fehler Die Windows PowerShell-Datendatei "DSC_PendingReboot.data.psd1" kann nicht im Verzeichnis "C:\ProgramFiles\WindowsPowerShell\Modules\ComputerManagementDsc\8.4.0\DscResources\DSC_PendingReboot\de-DE\" oder einem übergeordneten Verzeichnis gefunden werden. fehlgeschlagen. Der lokale Konfigurations-Manager (LCM)       konnte Desired State Configuration nicht manuell starten.                                                                                                                                                                   
+ CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException                                                                                                                 
+ FullyQualifiedErrorId : ImportModuleFailed                                                                                                                                                                            
+ PSComputerName        : localhost                                                                                                                                                                                                                                                                                                                                                                                                         
AUSFÜHRLICH: Vorgang "CIM-Methode aufrufen" wurde abgeschlossen.                                                                                                                                                        
AUSFÜHRLICH: Die Ausführung des Konfigurationsauftrags hat 3.539 Sekunden gedauert.

#### Suggested solution to the issue

N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

PendingReboot "DisableReboot"
        {
            Name = "DisableReboot"
            DependsOn = "[Script]DisableRebootNodeIfNeeded"
            SkipCcmClientSDK = $true
            SkipComponentBasedServicing = $true
            SkipPendingComputerRename = $true
            SkipPendingFileRename = $true
        }

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-Bit
WindowsVersion       : 2004
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE}

#### Version and build of PowerShell the target node is running

PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

8.4.0

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR corrects Pending Reboot to use `Get-LocalizedData` to read data so that it will work on non en-US OS.

#### This Pull Request (PR) fixes the following issues

- Fixes #350 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing this one for me?

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/351)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/351#-:-MPTVaNl9Ss5tw1xHXWY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
Closing and reopening to kick off tests.

**Comment by PlagueHO** [comment]
@johlju - not sure why the ScheduledTask integration tests are failing on WS2019. I'll have to do some investigation into this. Will leave this open and raise another issue.

**Comment by PlagueHO** [comment]
@johlju - this is now fixed so can be reviewed.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/351#-:-MSxjl5V0kb1GUQE2lEy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
