### PR TITLE
WindowsCapability: Add 'Source' parameter when adding capability

### LINKED ISSUE #361: Consider adding 'Source' to WindowsCapability
Consider adding support for offline capability installs.

![image](https://user-images.githubusercontent.com/3605266/110530888-c795c900-80cf-11eb-8bb3-975d9f37b83a.png)

current:

```powershell
WindowsCapability [String] #ResourceName                                                                                                                                                                                                               {                                                                                                                                                                                                                                                          Name = [string]
    [DependsOn = [string[]]]
    [Ensure = [string]{ Absent | Present }]
    [LogLevel = [string]{ Errors | Warnings | WarningsInfo }]
    [LogPath = [string]]
    [PsDscRunAsCredential = [PSCredential]]
}
```

proposed:

```powershell
WindowsCapability [String] #ResourceName                                                                                                                                                                                                               {                                                                                                                                                                                                                                                          Name = [string]
    [DependsOn = [string[]]]
    [Ensure = [string]{ Absent | Present }]
    [LogLevel = [string]{ Errors | Warnings | WarningsInfo }]
    [LogPath = [string]]
    [PsDscRunAsCredential = [PSCredential]]
    [Source =  [string]]
}
```

### PR DESCRIPTION
**Pull request by brwilkinson**
#### Pull Request (PR) description
Add Source parameter for when adding Windows Capabilities. Useful if you don't have Windows Update configured or Features on Demand. Also useful for Server 2022 preview which comes with a separate download for FOD.

#### This Pull Request (PR) fixes the following issues

This is a feature request not an issue.
    - Fixes #361 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/363)

### CODE REVIEW

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Sorry abut the delay in the review @brwilkinson - I was max capacity for last month. Just some minor tweaks but great stuff.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/363#-:-MXUzUBj90KrnHZVswLs:bhzbmek)* status: all files reviewed, 1 unresolved discussion (waiting on @brwilkinson)

___
*[CHANGELOG.md, line 8 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/363#-MXUysZCAhacfWvmF3xB:-MXUysZCAhacfWvmF3xC:b-bkziv7) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/871d3de253b4a3160629d8297c3c8cebc6dc4598/CHANGELOG.md#L8)):*
> ```Markdown
> ## [Unreleased]
> - WindowsCapability
>   - Added the 'Source' parameter for Add-WindowsCapability [Issue #361](https://github.com/dsccommunity/ComputerManagementDsc/issues/361)
> ```

Can you use the format:
```md
- Added the 'Source' parameter for Add-WindowsCapability as an
  optional parameter - Fixes [Issue #361](https://github.com/dsccommunity/ComputerManagementDsc/issues/361)
```

**Review by brwilkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/363)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 8 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/363#-MXUysZCAhacfWvmF3xB:-MXV4gzZ1iK4hkTzSyYl:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/871d3de253b4a3160629d8297c3c8cebc6dc4598/CHANGELOG.md#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use the format:
```md
- Added the 'Source' parameter for Add-WindowsCapability as an
  optional parameter - Fixes [Issue #361](https://github.com/dsccommunity/ComputerManagementDsc/issues/361)
```
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/363)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brwilkinson)

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/363#-:-MXV7Kwu9vKqofO8E2gc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brwilkinson)

**Pull request merged**
