### PR TITLE
Correct code coverage badge in README.md

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

Fixes the Code Coverage badge.

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing for me? Should be a quick one.

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/370)

### CODE REVIEW

**Review by kilasuit — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/370)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Comment by PlagueHO** [comment]
Thanks @kilasuit - can you review again? I missed a pipeline tweak to update to blog post (https://dsccommunity.org/blog/add-codecov-support-to-repository/).

**Review by kilasuit — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/370)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Review by johlju — APPROVED** [review]
:lgtm:

@kilasuit already reviewed it but I just went through the 10 or something PR's that you sent in in different repos, so I just figured I review this one too :smile: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/370#-:-MYeJACm87jEy4K_BHVA:bxnpxrl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Comment by johlju** [comment]
@PlagueHO We should have changed this one too (to PublishPipelineArtificat):

https://github.com/dsccommunity/ComputerManagementDsc/blob/5648a96b001ae16893ec893c63da7406756353ab/azure-pipelines.yml#L122-L127

**Pull request merged**
