### PR TITLE
Adds new resource DismFeature

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- ComputerManagementDsc
  - Added new resource DismFeature.

Deprecates the xDismFeature resource in the module xDismFeature. Suggest doing this instead of maintain a single resource module.

#### This Pull Request (PR) fixes the following issues
Partly issue https://github.com/PowerShell/DscResources/issues/374

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/319)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO let’s wait with this one as it seems this is no longer necessary. If there haven’t been any reported scenarios where this resource is necessary then I close this and just deprecate the xDismFeature repo. If there are scenarios for this in the future I will be keeping the working branch.

**Comment by PlagueHO** [comment]
@johlju - you might be right. What was the difference between using DISM and `*-WindowsFeature`? It seems like they cover the same area....

**Comment by johlju** [comment]
I’m not sure as I never have used DISM to install anything as far as I can remember. I sent a tweet and asked in #DSC channel but haven’t yet seen a scenario where it is needed. 
Maybe this pre-WindowsFeature (older OS:es that is no longer supported)

**Comment by PlagueHO** [comment]
Cool. Maybe a resource we could drop. I suspect it was for Windows Server 2008 R2 that didn't have the *-WindowsFeature cmdlets....

**Comment by johlju** [comment]
Closing this PR. There has not been any reported workloads that need this resource. If a resource for DISM is ever needed then I will keep the working branch, and the code will still exist in the closed PR for reference.

**Pull request closed without merging**
