### PR TITLE
BREAKING CHANGE: ScheduledTask: Update and fix existing task trigger parameters

### LINKED ISSUE #168: xScheduledTask stop all running tasks at the end of repetition duration"  ?
**Details of the scenario you tried and the problem that is occurring:**
Might just be being thick but is there no way to change the setting "stop all running tasks at the end of repetition duration" 

**The DSC configuration that is using the resource (as detailed as possible):**
xscheduledtask 4.0.0.0  (xcomputermanagement) 
**Version of the Operating System and PowerShell the DSC Target Node is running:**
server 2016 5.1
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
4.0.0.0

### LINKED ISSUE #282: Schedule Task run immediately
Hi, 
How do I get the scheduled task to start immediately and only once? Im using the ScheduledTask resource, but I can't get it to start and only run once?

### LINKED ISSUE #345: ScheduledTask: Delay parameter applicability
## Details of the scenario you tried and the problem that is occurring
According to documentation: 
>Delay | Write | String | Specifies a delay to the start of the trigger. The delay is a static delay before the task is executed. Can only be used in combination with ScheduleType OnEvent.

Is there a specific reason why Delay is only applicable to OnEvent ScheduleType?
Because while creating task in GUI, this parameter is applicable to every ScheduleType except `OnIdle` (where it is disabled, for obvious reasons) and `On a schedule` (where it is replaced by RandomDelay)

In my experience creating tasks with ScheduleType = AtStartup and AtLogon is a very common scenario, but setting delay for such tasks is currently not supported by the dsc resource.

#### Suggested solution to the issue

Delay parameter has to be applicable to ScheduleTypes `AtStartup`, `AtLogon` and other types to match behavior of GUI Task Scheduler editor.

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description

Updates and fixes various issues with task trigger parameters:
In theory we are only adding new interfaces but due to general ScheduledTask flakiness this is marked as a BREAKING CHANGE.

- Adds new Scheduled Types: OnIdle, AtCreation, OnSessionState
- Adds StateChange parameter to allow specifying which session state changes trigger the launch (requires OnSessionState schedule type to be set).
- Allows StartTime to be specified for all schedule types - the underlying variable (StartBoundary) is used by Windows for the 'Activate at' setting even on triggers other than 'Once', 'Daily' and 'Weekly'.
- Updated RandomDelay logic from a blacklist to a whitelist as it is only supported by a very small number of schedule types
- Added StopAtDurationEnd parameter
- Added TriggerExecutionTimeLimit parameter (will do much the same as ExecutionTimeLimit until this resource is updated to support multiple triggers, but the separate parameter does exist)
- Updated Delay parameter logic to reflect other TimeSpan based values, and support AtLogon, AtStartup, AtCreation and OnSessionState schedule types.
- Fixed User parameter to return the correct value instead of reflecting the Credential user value, plus updated logic for use with OnSessionState as well as AtLogon, and to be set if LogonType = Group, 

#### This Pull Request (PR) fixes the following issues

- Fixes #168
- Fixes #282
- Fixes #345 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437)

### CODE REVIEW

**Comment by Borgquite** [comment]
Still working on this - will hope to get more examples & sort tests imminently.

**Review by dan-hughes — COMMENTED** [review]
Good stuff. I noticed I missed changing the `Assert-MockCalled` in this file when I updated to Pester 5. Update your's and I'll create another PR for the rest. 

It looks like with the parameter and behaviour changes that is a breaking change. Can the PR title be updated to suit, unless you can convince me otherwise!

> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-:-O900BtV9cXI8U03NrvH:bvy39bd)* status: all files reviewed, 7 unresolved discussions (waiting on @Borgquite)

___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 686 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9-q-jQ-gB9Hz6EEPRp:-O9-q-jQ-gB9Hz6EEPRq:b-v92jvv) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/62ba94402e336d5a581daafb79c34061ec5b230f/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L686)):*
> ```PowerShell
>                 $triggerParameters.Add('AtLogon', $true)
> 
>                 if (-not [System.String]::IsNullOrWhiteSpace($User) -and $LogonType -ne 'Group')
> ```

Why is the `LogonType` check not required anymore?
___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 786 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9-stwV-3yELPJuUux2:-O9-stwV-3yELPJuUux3:brull6k) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L786)):*
> ```PowerShell
>                 $trigger = New-CimInstance -CimClass $cimTriggerClass -ClientOnly
>                 $trigger.Enabled = $true
>                 $trigger.StateChange = [UInt32][ScheduledTask.StateChange] $StateChange
> ```

Is the cast to a `UInt32` requied? 
If the Enum's align then this should be taken care of for you. 
___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 2125 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9-vTqZ9YQ4ochD_dPP:-O9-vTq_5aket18P1Dtj:baffczu) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L2125)):*
> ```PowerShell
>             EventValueQueries               = ConvertTo-HashtableFromTaskNamedValuePairCollection -Array $trigger.ValueQueries
>             Delay                           = ConvertTo-TimeSpanStringFromScheduledTaskString -TimeSpan $trigger.Delay
>             StateChange                     = [System.String][ScheduledTask.StateChange][UInt32] $trigger.StateChange # Cast to integer first to allow casting to enum with null
> ```

See the above comment on StateChange. Worse case scenario is the type needs qualifying.
___
*[`source/DSCResources/DSC_ScheduledTask/en-US/DSC_ScheduledTask.strings.psd1` line 0 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9-vuCU1lOu7vCaWzYG:-O9-vuCU1lOu7vCaWzYH:b-udzjbx) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/source/DSCResources/DSC_ScheduledTask/en-US/DSC_ScheduledTask.strings.psd1#L0)):*
Ideally these should have message Id's, I think let it go this time and bulk update them.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 3026 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O90-GNZ2d0MnrvuMLOL:-O90-GNZ2d0MnrvuMLOM:b-vrt6ds) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/tests/Unit/DSC_ScheduledTask.Tests.ps1#L3026)):*
> ```PowerShell
>             }
> 
>             Assert-MockCalled Register-ScheduledTask -Exactly -Times 1 -Scope It
> ```

`Assert-MockCalled` should be `Should -Invoke` in Pester 5.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 3123 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O90-yXG0jOMr7rQaW-I:-O90-yXG0jOMr7rQaW-J:b2nreh6) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/tests/Unit/DSC_ScheduledTask.Tests.ps1#L3123)):*
> ```PowerShell
>             }
> 
>             Assert-MockCalled Register-ScheduledTask -Exactly -Times 1 -Scope It
> ```

Same as above.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 3274 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9004vQ8lZk902IwwWm:-O9004vQ8lZk902IwwWn:b2nreh6) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/tests/Unit/DSC_ScheduledTask.Tests.ps1#L3274)):*
> ```PowerShell
>             }
> 
>             Assert-MockCalled Register-ScheduledTask -Exactly -Times 1 -Scope It
> ```

Same as above.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 3383 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9006bK6eN4P5y9VmDV:-O90-23P1BuWzi-AaLlF:b2nreh6) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/tests/Unit/DSC_ScheduledTask.Tests.ps1#L3383)):*
> ```PowerShell
>             }
> 
>             Assert-MockCalled Register-ScheduledTask -Exactly -Times 1 -Scope It
> ```

Same as above.

**Review by Borgquite — COMMENTED** [review]
Thanks - I've just updated them all though as quicker that way!

With regards to any breaking parameter changes:
* New ScheduleTypes - new functionality, shouldn't affect existing people
* StateChange - new parameter
* StartTime - should only affect someone who has defined a StartTime on something other than Once, Daily and Weekly (which is not currently valid for other schedule types, as the doco make clear). Is it a breaking change if someone is already doing something we've told them not to do?).
* RandomDelay - shouldn't affect existing functionality
* StopAtDurationEnd - new parameter
* TriggerExecutionTimeLimit - new parameter
* Delay - shouldn't affect existing functionality - again it only changes behaviour for someone who has already defined Delay on AtLogon, AtStartup type (again, it's not currently valid, as the doco makes clear).
* User - doesn't work at present (see below), a bug fix

I didn't think new functionality like these necessarily counted as a 'breaking' change but if I've misunderstood, fair enough :)

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-:-O99rsH10VV3XGvzTId5:bsnbjm3)* status: 14 of 17 files reviewed, 7 unresolved discussions (waiting on @dan-hughes)

___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 686 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9-q-jQ-gB9Hz6EEPRp:-O99uWApB0jmgXYvwPAX:b-e8lnze) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/62ba94402e336d5a581daafb79c34061ec5b230f/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L686)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Why is the `LogonType` check not required anymore?
</blockquote></details>

I think this is a bug, where the User trigger parameter has been confused with the ExecuteAsCredential parameter. The User parameter is set on an *trigger* as it 'Specifies the identifier of the user for a trigger that starts a task when a user logs on.' - this has nothing to do with the *principal* which the task logs on *as* which can still be a Group. 

I've checked this in the UI. It's perfectly possible to create a Task where the *Principal* is a group, but the AtLogon *Trigger* contains a specific user (i.e. 'run for anyone in this group, but for this particular trigger, only trigger for this specific user'). So the check blocks a potentially valid configuration and is therefore unnecessary.
___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 786 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9-stwV-3yELPJuUux2:-O9A-yHa-TVg9ivTEbqM:bn18yih) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L786)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Is the cast to a `UInt32` requied? 
If the Enum's align then this should be taken care of for you.
</blockquote></details>

Ah looks like you're right, this one isn't required - got a bit carried away when fixing the issue below...
___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 2125 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9-vTqZ9YQ4ochD_dPP:-O99xQH44P3iXu6J_qco:bytuzm3) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L2125)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

See the above comment on StateChange. Worse case scenario is the type needs qualifying.
</blockquote></details>

This was necessary for if an existing task's StateChange = $null (came up during testing) - running [ScheduledTask.StateChange]$null returns an error (see comment, and https://github.com/PowerShell/PowerShell/issues/3542). Casting to Unit32 first means that $null return 0, which is defined in the enum
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 3026 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O90-GNZ2d0MnrvuMLOL:-O99rcRCCaWsuE0D-hIb:b-896fix) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/tests/Unit/DSC_ScheduledTask.Tests.ps1#L3026)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

`Assert-MockCalled` should be `Should -Invoke` in Pester 5.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 3123 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O90-yXG0jOMr7rQaW-I:-O99rdPw3OI6cqJMVwyd:b-896fix) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/tests/Unit/DSC_ScheduledTask.Tests.ps1#L3123)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 3274 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9004vQ8lZk902IwwWm:-O99rdtS5IjCOgiJPP95:b-896fix) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/tests/Unit/DSC_ScheduledTask.Tests.ps1#L3274)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 3383 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9006bK6eN4P5y9VmDV:-O99reV42iWQWmqawA2S:bs7wumx) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/tests/Unit/DSC_ScheduledTask.Tests.ps1#L3383)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Review by dan-hughes — COMMENTED** [review]
Just a couple of things and it looks good to go.

There are some rules around what constitues `BREAKING` and an interface change is one of them. 

@johlju, @PlagueHO can you please provide your opinion on whether the above would mean a new major version release?

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-:-O9AA-JCDI47zEYdEkxk:b-ylagxi)* status: all files reviewed, 2 unresolved discussions (waiting on @Borgquite)

___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 2125 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9-vTqZ9YQ4ochD_dPP:-O9A9OMb3evhZTymFfGU:bi1fxak) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L2125)):*
<details><summary><i>Previously, Borgquite (Chris H) wrote…</i></summary><blockquote>

This was necessary for if an existing task's StateChange = $null (came up during testing) - running [ScheduledTask.StateChange]$null returns an error (see comment, and https://github.com/PowerShell/PowerShell/issues/3542). Casting to Unit32 first means that $null return 0, which is defined in the enum
</blockquote></details>

After a bit of testing here the `[UInt32]` is required. Can you fully qualify it e.g. with `System` but I don't believe the `[System.String]` is required as the enum should deal with this for you.@
___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 23 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9A8xtx4DnR9UL1Hc5C:-O9A8xtx4DnR9UL1Hc5D:b-40jfnt) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/aa83af1413beba6687ce951014e8e2c87e56b477/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L23)):*
> ```PowerShell
>         OnWorkstationLock,
>         OnWorkstationUnlock
>     }
> ```

There does not seem to be a DscCommunity 'convention' than I can find for this, but I would add the enum values and in this case the .NET type `uint` to help remove any potential type errors.



_Code quote:_
```PowerShell
    public enum StateChange
    {
        Undefined,
        OnConnectionFromLocalComputer,
        OnDisconnectFromLocalComputer,
        OnConnectionFromRemoteComputer,
        OnDisconnectFromRemoteComputer,
        OnWorkstationLock,
        OnWorkstationUnlock
    }
```
___
*[`tests/Unit/DSC_ScheduledTask.Tests.ps1` line 3026 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O90-GNZ2d0MnrvuMLOL:-O9A9pG98vv-HAGJ2YEo:b5z9drm) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/tests/Unit/DSC_ScheduledTask.Tests.ps1#L3026)):*
<details><summary><i>Previously, Borgquite (Chris H) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks for changing all of them.

**Comment by PlagueHO** [comment]
@dan-hughes - It'll be a BREAKING CHANGE if the interface changes would break existing configurations. Otherwise, it would just be a minor number increase. Looking through the change (briefly) the interface changes seemed to be mostly additive - but adding new parameters can still cause configs to break (or change behaviour).

My recommendation for this one though is to make it a BREAKING CHANGE. ScheduleTask is one of the most nitpicky resources (because of the different ways the Windows team implemented it - check the backlog of issues down to different implementations in Windows). It has a tendency to have various side effects and undocumented behaviors -especially between versions of the OS. So, I'd probably err on the side of caution for this one and just make it a BREAKING CHANGE. Rather be safe than sorry :grinning:

If I have time to review (and it's still open), come the weekend I'll have time.

**Comment by Borgquite** [comment]
@PlagueHO That makes sense. I have noted how weird the implementation seems to be. If I were starting from scratch it might have been better to implement the whole thing using Register-ScheduledTask and New-CimInstance (e.g. my example here) https://stackoverflow.com/a/78703118/12872270 as I'm guessing doing it at a low-level WMI/CIM objects might have circumvented the various weirdness in the abstraction layer the PowerShell New-ScheduledTask* cmdlets add. Of course that wouldn't avoid any OS-level issues. Nevermind. At least we're getting near to feature completeness now.

**Review by Borgquite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @dan-hughes)

___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 2125 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9-vTqZ9YQ4ochD_dPP:-O9EkwNO3lFxsZjwZoWl:b59opz2) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L2125)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

After a bit of testing here the `[UInt32]` is required. Can you fully qualify it e.g. with `System` but I don't believe the `[System.String]` is required as the enum should deal with this for you.@
</blockquote></details>

Have fully qualified - but if I remove [System.String], it stops Test-TargetResource returning true when resource is in the desired state (which is why it was in there in the first place) ?
https://dev.azure.com/dsccommunity/ComputerManagementDsc/_build/results?buildId=9571&view=logs&j=7d3af221-dd98-540f-35f6-de201108da76&t=0a82f033-7b8c-5c12-0fd5-dbd7a46d75ab
___
*[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 23 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9A8xtx4DnR9UL1Hc5C:-O9EkgbyA7Sv5o5lBdcn:b-vndefz) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/aa83af1413beba6687ce951014e8e2c87e56b477/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L23)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

There does not seem to be a DscCommunity 'convention' than I can find for this, but I would add the enum values and in this case the .NET type `uint` to help remove any potential type errors.
</blockquote></details>

Done. (And glad you asked me to do it - made me see that StateChange has a couple of outlying values at the end!) :)
https://learn.microsoft.com/en-us/windows/win32/taskschd/sessionstatechangetrigger-statechange

**Comment by dan-hughes** [comment]
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437)_ status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @dan-hughes)
> 
> _[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 2125 at r3](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9-vTqZ9YQ4ochD_dPP:-O9EkwNO3lFxsZjwZoWl:b59opz2) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/46226d357c67e2a2ae9cc7f700fe8aa83f993657/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L2125)):_
> 
> Previously, dan-hughes (Daniel Hughes) wrote…
> Have fully qualified - but if I remove [System.String], it stops Test-TargetResource returning true when resource is in the desired state (which is why it was in there in the first place) ? https://dev.azure.com/dsccommunity/ComputerManagementDsc/_build/results?buildId=9571&view=logs&j=7d3af221-dd98-540f-35f6-de201108da76&t=0a82f033-7b8c-5c12-0fd5-dbd7a46d75ab

Probably due to the schema being `[System.String]`. If it's needed then so be it.

> 
> _[`source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1` line 23 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-O9A8xtx4DnR9UL1Hc5C:-O9EkgbyA7Sv5o5lBdcn:b-vndefz) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/aa83af1413beba6687ce951014e8e2c87e56b477/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L23)):_
> 
> Previously, dan-hughes (Daniel Hughes) wrote…
> Done. (And glad you asked me to do it - made me see that StateChange has a couple of outlying values at the end!) :) https://learn.microsoft.com/en-us/windows/win32/taskschd/sessionstatechangetrigger-statechange

😊

**Review by dan-hughes — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Borgquite)

**Comment by dan-hughes** [comment]
@johlju, @PlagueHO, review complete.

**Review by Borgquite — COMMENTED** [review]
When I was browsing through the CHANGELOG for a different reason, I spotted #385 where someone else was trying to resolve the issue where the 'principal' username and the 'User' trigger parameter were conflated. Unfortunately the 'fix' was to continue the process of updating the User parameter based on the content of BuiltInAccount or other *principal*-related attributes, rather than fixing the bug in Get-TargetResource so that User is retrieved from the Trigger, not the Principal - i.e. the line below, which is fixed in this PR:

https://github.com/dsccommunity/ComputerManagementDsc/blob/62ba94402e336d5a581daafb79c34061ec5b230f/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L1925

This pull now removes all elements where the 'User' attribute is tierd into the 'principal' username. As far as I can see this bug crept in back in 2017 in the commit below. It's been largely unnoticed probably because not many people have needed to create an OnLogon or OnSessionState trigger, and therefore haven't seen the buggy behaviour.

https://github.com/dsccommunity/ComputerManagementDsc/commit/280e5c7f0e62e8f6d272effe18928971f174e988

Hope this finally resolves this.

  

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/437#-:-O9K22UJAjCo3nFxUhnn:b-96y81s)* status: 10 of 17 files reviewed, all discussions resolved (waiting on @dan-hughes)

**Comment by Borgquite** [comment]
(Fixing this uncovered another bug in my integration tests which was being masked by the previous behaviour so there's a change in those too)

**Comment by johlju** [comment]
Merging this. As it is a breaking change, any other issues can be resolved in other PRs 🙂

**Pull request merged**
