### PR TITLE
WindowsEventLog: Update MaximumSizeInBytes value in example

### PR DESCRIPTION
**Pull request by fullenw1**
#### This Pull Request (PR) fixes the following issues
The former value of 4096kb in the example does not work. And it's the same for any size unit like kb, mb, gb, ...

It generates the following error message:

> Compilation errors occurred while processing configuration 'DscConfigurationName'. Please review the errors reported in error stream and modify your configuration code appropriately.
>     + CategoryInfo          : InvalidOperation: (DscConfiguration:String) [], InvalidOperationException
>     + FullyQualifiedErrorId : FailToProcessConfiguration

Entering only a number works fine.

#### Task list
- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/278)

### CODE REVIEW

**Comment by fullenw1** [comment]
> <#PSScriptInfo
> .VERSION 1.0.0
 
> Can you update this value to 1.0.1 so that the example will get repushed to PSGallery?

Value updated.

**Comment by fullenw1** [comment]
> There seems to be a strange symbol at the end of this line - can you check this? Just want to make sure it doesn't cause a problem during release (sorry to nitpick  )

No worries!
I had to add some extra spaces to make Github jump to the next line. Now I remove them and added only a CR/LF character but it becomes one line again (with more than 80 characters).
How should I split this line?

**Comment by PlagueHO** [comment]
Doh! Can you resolve the conflicts for me @fullenw1 ? Sorry another PR got merged.

**Comment by PlagueHO** [comment]
Hi @fullenw1 - you should be able to just use a CRLF (enter) to move this to the next line :grin: nothing tricky!

**Comment by PlagueHO** [comment]
Hi @fullenw1 - oh, are you editing in GitHub?

**Comment by fullenw1** [comment]
> Hi @fullenw1 - oh, are you editing in GitHub?

Yes :-)

**Comment by PlagueHO** [comment]
@fullenw1 - ah right - that will be why. You're best off editing in VS Code. Are you able to do that?

**Comment by fullenw1** [comment]
> @fullenw1 - ah right - that will be why. You're best off editing in VS Code. Are you able to do that?

Yes I did that before the last merge :)

If I'm right everything is now merged into patch1.
What's the next step?
It seems there is a conflict...

**Comment by PlagueHO** [comment]
Hi @fullenw1 - it looks like there are some conflicts to resolve. If you can resolve them then I'll review.

**Comment by fullenw1** [comment]
Hi @PlagueHO 

It should be ok now :)

**Comment by PlagueHO** [comment]
Hi @fullenw1 - appologies, this got closed when I deleted Dev (we no longer use Dev). Can you possibly resubmit the PR against master and I'll get it merged?

**Comment by fullenw1** [comment]
> Hi @fullenw1 - appologies, this got closed when I deleted Dev (we no longer use Dev). Can you possibly resubmit the PR against master and I'll get it merged?

Hi @PlagueHO ,

How can I achieve this? Do I have to start all from the beginning again? :)

**Comment by PlagueHO** [comment]
Hi @fullenw1 - you could rebase your branch against the new master branch, but if you're not familiar with rebase then it is a bit tricky (but a great skill to learn).

As the structure of the repo has changed quite a bit it might just be simpler to redo the change as it wasn't too large.

Again, sorry about that.

**Pull request closed without merging**
