### PR TITLE
PSResourceRepository: Add property `Reasons`

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description

- PSResourceRepository
  - The resource now supports the read-only property `Reasons` that the
    compliance part (audit via Azure Policy) of Azure AutoManage Machine
    Configuration uses.

#### This Pull Request (PR) fixes the following issues

None.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402)

### CODE REVIEW

**Comment by johlju** [comment]
@nickgw if you have time, it would be great if you could help to review this one. 🙂

**Comment by johlju** [comment]
So there is an issue using the property `Reasons` using type `[Reason]`. Reproduced by @nyanhp, configuration script fail to parse when two modules (psm1 files) contain the class `Reason`. Same happens for MOF-based resources.

image

@nyanhp created a repository that shows the issue with both class-based resources and MOF-based resources.

**Comment by johlju** [comment]
Closing this PR until there is a solution for this, but most likely not gonna be a fix for WMF5.x.

**Comment by johlju** [comment]
Seems there is a fix for this, will update this PR.

**Comment by johlju** [comment]
This PR should be changed according to https://github.com/dsccommunity/DscResource.Base/issues/4. It should also wait for PR #405 is merged so we don't need to do the same modification in this module as being done in DscResource.Base.

**Comment by johlju** [comment]
@PlagueHO this one is now ready for review. The module DscResource.Base got a fix that was released as v1.1 to support this change.

_I will fix the resources over at SqlServerDsc the same way._

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[`CHANGELOG.md` line 15 at r3](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402#-NPGdioVBUR_Z9fF1WIu:-NPGdioVBUR_Z9fF1WIv:undefined) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/bfa59830399e01d0003f27cfccebe71c82c4dee8/CHANGELOG.md#L15)):*
> ```Markdown
>     build pipeline.
> - PSResourceRepository
>   - The resource now supports the read-only property `Reasons` that the compliant
> ```





_Suggestion:_
```Markdown
  - The resource now supports the read-only property `Reasons` that the compliance
```
___
*[`CHANGELOG.md` line 16 at r3](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402#-NPGddbD70GW6LLftpu_:-NPGddbD70GW6LLftpua:b45h) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/bfa59830399e01d0003f27cfccebe71c82c4dee8/CHANGELOG.md#L16)):*
> ```Markdown
> - PSResourceRepository
>   - The resource now supports the read-only property `Reasons` that the compliant
>     part (audit via Azure Policy) of the Azure AutoManage Machine Configuration
> ```





_Suggestion:_
```Markdown
part (audit via Azure Policy) of Azure AutoManage Machine Configuration
```

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 15 at r3](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402#-NPGdioVBUR_Z9fF1WIu:-NPIC1v161gqOVF8nUnM:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/bfa59830399e01d0003f27cfccebe71c82c4dee8/CHANGELOG.md#L15)):*
> ```Markdown
>     build pipeline.
> - PSResourceRepository
>   - The resource now supports the read-only property `Reasons` that the compliant
> ```

Done.
___
*[`CHANGELOG.md` line 16 at r3](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402#-NPGddbD70GW6LLftpu_:-NPIC2V1Cly26h0TgV7n:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/bfa59830399e01d0003f27cfccebe71c82c4dee8/CHANGELOG.md#L16)):*
> ```Markdown
> - PSResourceRepository
>   - The resource now supports the read-only property `Reasons` that the compliant
>     part (audit via Azure Policy) of the Azure AutoManage Machine Configuration
> ```

Done.

**Comment by johlju** [comment]
@PlagueHO this good to continue reviw and merge if everything looks good. I couldn't find an easy way to return a hashtable for the property `Reason` to avoid the need for a unique class in each module, but couldn't find a way, so I reverted to using a uniqe class instead (`CMReason`, and in SqlServerDsc it will be called `SqlReason`). The important part is that the object that is returned have the correct properties. I also added an integration test to verify the property `Reason` by using `Invoke-DscResource` that calls the method `Get()`.

**Review by PlagueHO — APPROVED** [review]
One tiny nit:

> Reviewed 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402#-:-NQ48TClCgjWDxYu0uwT:b93fnky)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`tests/Unit/Classes/CMReason.Tests.ps1` line 54 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402#-NQ48JP76CLJjXQxF6XE:-NQ48JP76CLJjXQxF6XF:bb70wkm) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff82f7b24714206493f07a0b5d48746829d63184/tests/Unit/Classes/CMReason.Tests.ps1#L54)):*
> ```PowerShell
>         }
> 
>         Context 'When setting an reading values' {
> ```

Nit:



_Suggestion:_
```PowerShell
Context 'When setting and reading values' {
```

**Review by johlju — COMMENTED** [review]
Fixed tiny nit. :slightly_smiling_face: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402#-:-NQ6463oCxSD7xQK3Msq:b7tyo0e)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402#-:-NQ89YkqDDe59Qu-1002:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

**Review by PlagueHO — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/402)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Pull request merged**
