### PR TITLE
ScheduledTask: Fixed execution account missing domain name

### LINKED ISSUE #352: ScheduledTask - Integration Test Failure on WS2019
The Integration tests for ScheduledTask on WS2019 have recently started failing:
https://dev.azure.com/dsccommunity/ComputerManagementDsc/_build/results?buildId=3431&view=logs&j=de978ee2-68a1-58a4-df18-d6018fff7e0b&t=801c2256-98eb-5af5-3ad4-305ba4a92848&l=4402
https://dev.azure.com/dsccommunity/ComputerManagementDsc/_build/results?buildId=3431&view=logs&j=de978ee2-68a1-58a4-df18-d6018fff7e0b&t=801c2256-98eb-5af5-3ad4-305ba4a92848&l=4532

It appears that it occurs in context "[ExecuteAs] No scheduled task exists but it should".

It seems to occur because the `ExecuteAsCredential` does not return the machine name on WS2019:

VERBOSE: [WIN-0UFA3MDU8F8]:                            [[ScheduledTask]ScheduledTaskExecuteAsAdd] NOTMATCH: Value (type
 'System.String') for property 'ExecuteAsCredential' does not match. Current state is 'VssAdministrator' and desired 
state is 'WIN-0UFA3MDU8F8\VssAdministrator'. (DRC0021)
VERBOSE: [WIN-0UFA3MDU8F8]:                            [[ScheduledTask]ScheduledTaskExecuteAsMod] NOTMATCH: Value (type
 'System.String') for property 'ExecuteAsCredential' does not match. Current state is 'VssAdministrator' and desired 
state is 'WIN-0UFA3MDU8F8\VssAdministrator'. (DRC0021)

If we compare this on WS2016:
VERBOSE: [fv-az433-359]:                            [[ScheduledTask]ScheduledTaskExecuteAsAdd] MATCH: Value (type 
'System.String') for property 'ExecuteAsCredential' does match. Current state is 'fv-az433-359\VssAdministrator' and 
desired state is 'fv-az433-359\VssAdministrator'. (DRC0020)
VERBOSE: [fv-az433-359]:                            [[ScheduledTask]ScheduledTaskExecuteAsMod] MATCH: Value (type 
'System.String') for property 'ExecuteAsCredential' does match. Current state is 'fv-az433-359\VssAdministrator' and 
desired state is 'fv-az433-359\VssAdministrator'. (DRC0020)

Therefore it appears that some recent change to WS2019 has caused this change.

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description

Improved PR #351 to include domain accounts.

#### This Pull Request (PR) fixes the following issues
Fixes #352
Possibly fixes or Improves #144

#### Task list
- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/356)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @jensotto - thanks for submitting this. It looks like the HQRM tests are failing because an entry hasn't been added to the CHANGELOG.md: See the `Update the Changelog` section in: https://dsccommunity.org/guidelines/contributing/

**Comment by jensotto** [comment]
It already contains a message for that change so I didn't add any further comments: Fixed issue with ExecuteAsCredential not returning fully qualified username on newer versions of Windows 10 and Windows Server 2019 - Fixes Issue #352.

**Comment by PlagueHO** [comment]
Ah, I see. Unfortunately for the tests to pass you'll need to make a correction message.

**Comment by jensotto** [comment]
Ok, I have mad a small change to the existing entry in changelog.

**Comment by PlagueHO** [comment]
Hi @jensotto - sorry about the delays in getting to this. Can you resolve the conflicts and I'll review?

**Comment by jensotto** [comment]
@PlagueHO conflicts resolved

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Thanks @jensotto - just some minor style tweaks to line length then can merge.

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/356#-:-MXpcimN18y8SPR4Eye_:b-q73ljc)* status: all files reviewed, 2 unresolved discussions (waiting on @jensotto)

___
*[source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1, line 1453 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/356#-MXpcHEi7IPkar4MmCK6:-MXpcHEi7IPkar4MmCK7:ba6rfai) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/2a0ae298d575e95c79995639907e712bc1e6afcb/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L1453)):*
> ```PowerShell
>         if ($username -match "$ENV:COMPUTERNAME\\" -and $currentValues.ExecuteAsCredential)
>         {
>             $currentValues.ExecuteAsCredential = Set-DomainNameInAccountName -AccountName $currentValues.ExecuteAsCredential -DomainName $ENV:COMPUTERNAME
> ```

Can you reduce the line length of this line by using:
```powershell
$currentValues.ExecuteAsCredential = Set-DomainNameInAccountName `
    -AccountName $currentValues.ExecuteAsCredential `
    -DomainName $ENV:COMPUTERNAME
```
___
*[source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1, line 1458 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/356#-MXpcS3p3Uv5oXIriZvU:-MXpcS3p3Uv5oXIriZvV:b-jvfbph) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/2a0ae298d575e95c79995639907e712bc1e6afcb/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L1458)):*
> ```PowerShell
>         if ($username -match "$ENV:USERDOMAIN\\" -and $currentValues.ExecuteAsCredential)
>         {
>             $currentValues.ExecuteAsCredential = Set-DomainNameInAccountName -AccountName $currentValues.ExecuteAsCredential -DomainName $ENV:USERDOMAIN
> ```

Can you reduce the line length of this line by using:
```powershell
$currentValues.ExecuteAsCredential = Set-DomainNameInAccountName `
    -AccountName $currentValues.ExecuteAsCredential `
v    -DomainName $ENV:USERDOMAIN
```

**Review by jensotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/356)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1, line 1453 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/356#-MXpcHEi7IPkar4MmCK6:-MXppmO2BcQNw1tAKeyf:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/2a0ae298d575e95c79995639907e712bc1e6afcb/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L1453)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you reduce the line length of this line by using:
```powershell
$currentValues.ExecuteAsCredential = Set-DomainNameInAccountName `
    -AccountName $currentValues.ExecuteAsCredential `
    -DomainName $ENV:COMPUTERNAME
```
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1, line 1458 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/356#-MXpcS3p3Uv5oXIriZvU:-MXppn7zC0GbcLn375Yz:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/2a0ae298d575e95c79995639907e712bc1e6afcb/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L1458)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you reduce the line length of this line by using:
```powershell
$currentValues.ExecuteAsCredential = Set-DomainNameInAccountName `
    -AccountName $currentValues.ExecuteAsCredential `
v    -DomainName $ENV:USERDOMAIN
```
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/356#-:-MXq0Y_Q9nMwwelDFgCQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jensotto)

**Pull request merged**
